### ISSUE TITLE
Some sims take a while to load (offline) on IE11

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/joist#164]
First noticed doing an offline test on IE11 of Area Builder. 

After opening the single-file HTML file, right-click and select 'Open with', choose Internet Explorer.

Sims I noticed take a while to load (around 1 minute on my Win7 machine):
Area Builder
Beer's Law Lab
pH Scale

Sims that don't seem to be affected:
Balancing Act
Color Vision

**Comment by jbphet** [comment]
Testing this on the currently deployed version of Area Builder, which is 1.0.1.  I downloaded the HTML file from the web site and opened it using right-click->Open with->Internet Explorer.  I did three trials, and all took 24 seconds, where 'loaded' is defined as the point where the home screen appears.  In all cases, the active area of the tab in IE was white for most of the load time, then the PhET logo is seen at about 22 seconds, then the home screen appears.

Opening using ctrl-o when in a tab yields the same time, i.e. 24 seconds to load.

Using ctrl-o with the console open yields the following output (I think the google part is because that's the page the browser was showing when the load was started):

>DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
>File: www.google.com
>HTML1300: Navigation occurred.
>File: area-builder_en.html
>DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
>File: www.google.com
>HTML1424: Invalid character
>File: area-builder_en.html, Line: 91, Column: 15170
>HTML1424: Invalid character
>File: area-builder_en.html, Line: 99, Column: 4803

**Comment by jbphet** [comment]
I built Area Builder from the current master, and the behavior is a bit different, and is somewhat similar to what @samreid described above.  A dialog is shown that says that IE has blocked the script from running scripts appears.  It looks like this:
![ie-message](https://cloud.githubusercontent.com/assets/3082831/8094386/118b94fe-0f84-11e5-956a-ac2d4e73dbd4.png)
If I don't press the "Allow blocked content" button, the sim never loads.  Once this button is pressed, the sim takes about 25 seconds to load - very comparable to what was seen with the published version.

So, it would appear that the "invalid character" issue had little or nothing to do with the long load time.

**Comment by jbphet** [comment]
Version info for IE11 used in the two tests described immediately above:
![ie-version](https://cloud.githubusercontent.com/assets/3082831/8094518/db1c5c40-0f84-11e5-8fbf-6da2eb1c8460.png)

**Comment by jonathanolson** [comment]
I don't see the MOTW (https://msdn.microsoft.com/en-us/library/ms537628%28v=vs.85%29.aspx) that we have for Flash sims in our built HTML5 sims. I'll test adding it.

**Comment by jbphet** [comment]
@oliver-phet said in the original problem description that some other sims, such as Balancing Act, didn't have this problem, but I just tested the published version of Balancing Act (v1.0.2) and it took 25 seconds, basically the same amount of time as Area Builder.

**Comment by jonathanolson** [comment]
Just testing, if I press "Allowed blocked content", it loads almost instantly. Adding the MOTW and loading causes it to freeze for ~15 seconds, but then loads instantly every time after to launch it. Testing more.

**Comment by jonathanolson** [comment]
Confirmed that sims built with this at the top of the template freeze the tab but don't ask for allowing blocked content:
```html
<!DOCTYPE HTML>
<!-- saved from url=(0025)http://phet.colorado.edu/ -->
<html>
```
Every launch after that is fast.

**Comment by jbphet** [comment]
The MOTW isn't work for me so far.  After manually adding it to the downloaded area-builder_en.html file, I'm still seeing the dialog message about blocked content, and it still takes about 24 seconds to load after pressing the button.

**Comment by jbphet** [comment]
I changed my IE settings to allow active content to run from files on My Computer, and things have changed, but this didn't really fix the issue.  Sometimes the dialog below appears for a while before the page loads, but the page does load:
![ie-ba-msg](https://cloud.githubusercontent.com/assets/3082831/8095683/738ad1b6-0f8d-11e5-8bfb-b97e99b12058.png)
This seems like an odd message, since this was an HTML file located on the local file system using the right-click->Open with method.

With these new settings, sometimes the sim will open with no dialogs, but still takes a long time to load, and occasionally it loads quickly.  I have yet to discern a pattern.

**Comment by jbphet** [comment]
I tested a local installation using IE11 and found that the same issue exists when trying to launch sims from within the local PhET mirror.  Not good.

**Comment by jbphet** [comment]
Discussed during the 6/11/2015 developer meeting, and we decided that we should continue to pursue a solution for this, since it feels quite broken for an HTML sim to take ~25 seconds to load.

**Comment by jonathanolson** [comment]
Notables from last night:
1. Windows-style "\r\n" is required after the MOTW for IE to parse it.
2. Amount of frozen time seems to be related to the existence of the code, not whether it is run.

**Comment by jonathanolson** [comment]
Also notable: http://windowssecrets.com/forums/showthread.php/165004-IE-Very-Slow-to-Open-htm-Files-Saved

**Comment by jonathanolson** [comment]
Closed after confirmed testing.
