### ISSUE TITLE
Too many license links in the about dialog

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#274]
See screenshot:

![image](https://cloud.githubusercontent.com/assets/679486/8641430/63d46f44-28d2-11e5-8242-581f50558b1f.png)

It has "Terms, Privacy and Licensing" as well as "Software Agreement and Licensing".  Why?  Perhaps one of them should be deleted?

**Comment by pixelzoom** [comment]
@zepumph Is this related to https://github.com/phetsims/joist/issues/163?

**Comment by pixelzoom** [comment]
@zepumph A couple of things related to this...

I suspect that you're not running with the 'phet' branch of the brand repository, which is why you didn't see the existing license link. If you run with the 'master' branch of brand, you'll be using the default (empty) brand, which currently has no links field in Brand.js.

And speaking of the "links" field in Brand.js... Notice that the license link is handled in Brand.js.  I suspect that the Translation Credits link may also need to be brand-specific too.  If that's the case, then inserting the sim name into the URL may be a little trickier than what you've done here.

Finally, af931a6ebf8f831c1857d485421b0c1240286df3 shows reformatting of code in AboutDialog.js that is not related to this issue (around line 69, `children.push(...`).  Are you using the PhET code style in IntelliJ IDEA?

**Comment by pixelzoom** [comment]
AboutDialog.js line 121 has a console.log that needs to be removed.

**Comment by pixelzoom** [comment]
AboutDialog.js line 105 has a private static function declared inside the constructor:

`var displayNameToDevName = function(...`

This will cause a copy of this function to be created for every instance of this type. In general, declare private static functions outside of the constructor to conserve memory.

**Comment by pixelzoom** [comment]
AboutDialog.js line 121 needs to be removed:

`console.log(devName)`

The lack of spacing around parens is another clue that you're probably not using the PhET code style.

**Comment by pixelzoom** [comment]
Moving some comments to #163 that I accidentally put here. Then I'll delete them here.

**Comment by zepumph** [comment]
Yeah this is my bad, I apologize, It will be fixed with commits related to #163.

**Comment by zepumph** [comment]
Closing
