### ISSUE TITLE
Navigation Bar Screen Buttons should be centered horizontally

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#282]
Previously the navigation bar screen buttons were centered horizontally. In #241 the navigation bar layout was reimplemented to facilitate internationalization--however the navbar screen icon centering was omitted.  Here is a screenshot of before/after, indicating the center line:

![centered](https://cloud.githubusercontent.com/assets/679486/8779688/c78c3d9c-2ec1-11e5-8115-59fedf5c5b9c.png)

This was discovered during #279.  I recommend to re-center these buttons in the navbar.  This is important in simulations with bilateral symmetry and/or sims which indicate the center, such as Forces and Motion: Basics, and I would recommend it as a generally good rule of layout design.  Also, on devices like iPad, having the button slightly off-center could make the UI feel lopsided.

I'll mark this as S2015R though it is up for discussion whether this is essential to complete before today's Molecule Shapes deployment.

**Comment by samreid** [comment]
The layout code has the screen buttons centered in the navbar like so:

```js
this.screenButtonsParent.center = this.background.center;
```

so to diagnose the problem, I added a red tick mark for the center of the navbar, and a green bounds around the screen buttons parent and I observed:

![image](https://cloud.githubusercontent.com/assets/679486/8782136/a5a0c536-2ed0-11e5-9e31-cfb33d852d4d.png)

So it looks like the different screen buttons do not have the same width/bounds/something.

**Comment by jessegreenberg** [comment]
@samReid I think this is happening because the buttons now have different widths.  The overlays on published navigation bar buttons all used to be as wide as the widest button.  Now each button has a uniquely sized overlay. Illustrated in the following:

master:
![ms_local_bounds](https://cloud.githubusercontent.com/assets/6396244/8782207/25233078-2ed1-11e5-9a46-11327f618e6d.PNG)
published:
![ms_dev_bounds](https://cloud.githubusercontent.com/assets/6396244/8782203/22d134aa-2ed1-11e5-9640-ed4dc226cdb3.PNG)


Since the screen buttons currently have less overlay space in master, buttons are getting shifted differently in master than in published versions.

**Comment by jonathanolson** [comment]
Worked with @samreid on the above fix, will let him decide whether to close the issue.

**Comment by samreid** [comment]
I added some comments in the above commit.  Next I'll just double check the overall centering in Photoshop.

**Comment by samreid** [comment]
I tested molecule shapes snapshot metrics in Photoshop and it looks pixel perfect, thanks @jonathanolson.  Closing.
