### ISSUE TITLE
navigation bar fails i18n layout test

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#299]
This occurs with the "adapted from PhET" brand (the default).

Example:
http://localhost/~cmalley/Github/hookes-law/hookes-law_en.html?dev&stringTest=SomeVeryLongStringThatMayCauseProblems

![screenshot_594](https://cloud.githubusercontent.com/assets/3046552/9689292/542a8746-52f2-11e5-8215-3e53f61057a0.png)

Assigning to @jonathanolson, since he most recently worked on navbar layout in https://github.com/phetsims/joist/issues/283.  The layout needs to be tested for all PhET brands, and with the 3 stringTest values that testers are using; `stringTest=X` for short strings, `stringTest=double` and `stringTest=SomeExtremelyLongStringThatWouldLikelyBreakSomething`.

**Comment by pixelzoom** [comment]
@jonathanolson Also note that the screen icons in the navbar are appearing in the reverse order in the above screenshot!

**Comment by jonathanolson** [comment]
The adapted-by text pushed the "available space on the right" metric to the negative. I've commited a limit to 60px for it (our text is 39px wide) as the best probable fix.

It was buggy (and reversed), since the "phet menu + home button" took up more than half the screen width, and the layout tries to fit the center of the screen buttons in the middle.

Let me know if this is a sufficient fix. Screenshot:
![navbar-some-long](https://cloud.githubusercontent.com/assets/480878/9696398/4e5b1c6a-532c-11e5-8665-185b3557c598.PNG)

**Comment by pixelzoom** [comment]
Looks sufficient to me. Closing.
