### ISSUE TITLE
Fullscreen HTTPS-only for Chrome

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#302]
We'll want to test once this goes live. We already have HTTPS links on https://github.com/phetsims/website/issues/289, but we want to make sure a full-screen button doesn't erroneously show up when running with HTTP.

Discussion in the Google Group seems to indicate it's likely that the fullscreenEnabled flag will be set (https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/2LXKVWYkOus%5B176-200%5D), but it's unclear fully.

Warning issues: https://code.google.com/p/chromium/issues/detail?id=481604 and implementation issue: https://code.google.com/p/chromium/issues/detail?id=464874

Will revisit when we hear more news about this change.

**Comment by pixelzoom** [comment]
> We'll want to test once this goes live. 

@jonathanolson This issue is 1+ year old. Has this gone live? Have we tested?

**Comment by jonathanolson** [comment]
I just tested. When I change the URL to access the sim over HTTP, the Full Screen button exists and works properly (on Chrome OSX).

I don't believe we made an effort to hide the button. Would warrant further investigation if we need to.

@ariel-phet, should we have someone investigate?

**Comment by ariel-phet** [comment]
@jonathanolson it seems in the current state of the website, someone would have to purposely use HTTP since we are default serving from HTTPS, that seems like a rare use case. Also at worst the user will try to go full screen and it won't work from HTTP and give some kind of security warning.

This does not seem to warrant any time to try to hide the button or such in my view. Closing
