### ISSUE TITLE
handle language direction in layout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#308]
This issue was generalized from https://github.com/phetsims/rosetta/issues/102 and affect many common repositories, as well as sim-specific code.

@ariel-phet says there's no time to work on this now, but should be on our radar for the future.

**Comment by arouinfar** [comment]
Off the top of my head, I can think of a few things that could be adjusted for RTL locales. When the time comes to work on this issue, I'd be happy to discuss it more with the developers. 

* In general, any left-aligned text should become right-aligned.
* Many control panels will need to be adjusted, so that the title precedes the readout/slider/combo box.

![image](https://cloud.githubusercontent.com/assets/8419308/11220789/d22ca032-8d1e-11e5-862a-efa1604f980f.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/11220796/dab8ee72-8d1e-11e5-8a27-823db53c26f1.png)
![image](https://cloud.githubusercontent.com/assets/8419308/11221221/24913318-8d21-11e5-8766-d41560425c0e.png)
* Control panels often have a checkbox/radio button, text, and an icon on the same line. For RTL, it should probably be reversed (Icon, Text, Checkbox/Radio Button).
![image](https://cloud.githubusercontent.com/assets/8419308/11221190/f6d12e6a-8d20-11e5-8b79-e5a049dfac43.png) ![image](https://cloud.githubusercontent.com/assets/8419308/11221404/2d1c2f32-8d22-11e5-8ef8-4fdb88b0120c.png)

* There are also times where text appears next to an icon. In RTL locales, the order should be reversed. 
![image](https://cloud.githubusercontent.com/assets/8419308/11221755/fa801b2c-8d23-11e5-9a59-987709b6a416.png) ![image](https://cloud.githubusercontent.com/assets/8419308/11221763/08e6759e-8d24-11e5-8df6-336188439d10.png)

**Comment by samreid** [comment]
A few years ago, someone proposed the following strategy for dealing with RTL simulations:

1. Horizontally flip the entire simulation
2. Horizontally flip all of the text

@arouinfar how close would this get us to the "ideal" case for RTL layout?

**Comment by pixelzoom** [comment]
I'm not sure that horizontally flipping applies to all UI components. For example, should the min/max be flipped on a slider? 

I'm also not sure that the same convention applies to all RTL languages.

**Comment by pixelzoom** [comment]
I seriously doubt that PhET will ever localize layout.  There are so many questions, it would be a huge amount of work, and it's unclear whether it even matters.

@ariel-phet Do you want to keep this issue open?

**Comment by ariel-phet** [comment]
@pixelzoom I think I agree. We have plenty of RTL users and they seem adaptable enough for this not to be a huge deal. It would be one thing if an RTL funder came to us with this as one of the stipulations for funding, but for the foreseeable future it seems like too big of an issue to tackle.
