### ISSUE TITLE
Scale the splash screen logo based on the size of the screen

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#309]
Everything in a PhET simulation scales to fit the window _except_ the splash screen logo/text.  Should this scale as well?  Tagging @ariel-phet @pixelzoom for discussion.

**Comment by ariel-phet** [comment]
I suppose that would be nice, but seems extremely low priority unless it would make the code cleaner/more consistent.

**Comment by pixelzoom** [comment]
I wouldn't bother with this, unlikely that the user will resize the browser window while the sim is loading, and if they do, not big deal because it doesn't compromise functionality of the sim.  Consider addressing this if/when animation is added to the splash, in https://github.com/phetsims/joist/issues/68.

**Comment by samreid** [comment]
I suspect this issue will become more important if/when we start targeting smaller devices (where the logo currently fills the whole screen or even goes offscreen).

**Comment by pixelzoom** [comment]
Folded this issue into #309, where the splash screen is getting a redesign.
