### ISSUE TITLE
Cannot dismiss non-modal dialogs

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#314]
As reported by @Cooookie in https://github.com/phetsims/joist/pull/312, it is impossible to dismiss non-modal dialogs.  I have reproduced the problem and I have a good solution in my working copy.  The Joist dialog demo is working properly.  I'll commit shortly.

**Comment by samreid** [comment]
In the above commit, I gave `barrierStack` a more appropriate name, added properties for `isShowing` into the Dialogs (rather than checking the formerly-known-as `barrierStack`).  I tested the joist dialog demo as well as molecules and light and did not see any issues.  @pixelzoom can you spare time to review these changes?

**Comment by pixelzoom** [comment]
For the record, I think `barrierStack` was a superior name, since this barrier can theoretically be used by things other than modal dialogs. By renaming to `modalNodeStack`, you've given the impression that it's for use by modal dialogs only.  While that may be the case, the documentation at Sim.js line 458 indicates that it has a more general use - to block input events:

```js
    // @public (joist-internal) - Semi-transparent black barrier used to block input events when a dialog
    // (or other popup) is present, and fade out the background.
    this.modalNodeStack = new ObservableArray(); // {Node} with node.hide()
```

If you want to proceed with calling it `modalNodeStack`, then the above doc should be revised to indicate that it's for use by modal dialogs only. 

In either case, it's not clear when `modalNodeStack` is marked `@public`, since it's not used outside of Sim.js.

**Comment by samreid** [comment]
I fixed the docs above to read like so:

```js
    // @private list of nodes that are "modal" and hence block input with the barrierRectangle.  Used by modal dialogs
    // and the PhetMenu
    this.modalNodeStack = new ObservableArray(); // {Node} with node.hide()

    // @public (joist-internal) Semi-transparent black barrier used to block input events when a dialog (or other popup)
    // is present, and fade out the background.
    this.barrierRectangle = new Rectangle( 0, 0, 1, 1, 0, 0, {
      fill: 'rgba(0,0,0,0.3)',
      pickable: true
    } );
```

This stack is used by both modal dialogs and the PhetMenu, so I'm considering the PhetMenu a "modal node" (coining a new phrase) because it behaves like a modal dialog (background fades, clicking away will dismiss it) without being a dialog.

I fixed the visibility annotations and updated the docs.

**Comment by pixelzoom** [comment]
:+1: Closing.
