### ISSUE TITLE
About dialog fails stringTest

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#319]
Not sure how this got through all the i18n testing for S2015R. But the About dialog fails the i18n string test.  It totally lacks any `maxWidth` settings.  Affects all sims.

Eg, with `?stringTest=long`:

![screenshot_10](https://cloud.githubusercontent.com/assets/3046552/12996255/8b36cf16-d0eb-11e5-8086-15327c0cc73f.png)

**Comment by jonathanolson** [comment]
Added constraints for:
1. Individual elements of the About dialog.
2. Individual elements in the PhET menu.
3. "Update" status nodes (from "Check for udpates...").

@ariel-phet, do we need to look into maintenance releases?
@pixelzoom, does the above commit look good (if you want/have time to review?)

**Comment by pixelzoom** [comment]
Commit looks good to me, tested with stringTest=long and stringTest=double.

Imo, we don't need to do maintenance releases for this.  The About dialog generally looked good with stringTest=double, and stringTest=long is a bit of a stress test.

**Comment by ariel-phet** [comment]
I do believe the about dialog was mentioned at some point, but deemed not so important, I would have to look over. (I also don't think we had stringTest=long when we were making some of those decisions)

But I am surprised ..certain things in the about dialog should NOT be translatable. 
- The version number (fine for the word version, but the number should not be able to be touched)
- Again, tittles in our translation credits, but our Names should not be able to be touched

@pixelzoom I will mention I have looked at the about dialog in some translated sims, nothing looked fishy, but that is probably because translators were doing a good job.

@jonathanolson no need for maintenance releases. But I would like the above concerns addressed in terms of things that should not be able to be translated

**Comment by jonathanolson** [comment]
> The version number (fine for the word version, but the number should not be able to be touched)

To support i18n, the order of the version text and version number itself is variable, and the English string is "version {0}". There are many places where a translator can omit the {0} in sims (and a number or something won't show up), so I don't think it's different here?

For names, same thing:
```
  "credits.softwareDevelopment": {
    "value": "Software Development: {0}"
  },
```.

> but our Names should not be able to be touched

It would be possible to ensure that {0} (or other patterns) would appear at least once, via metadata for the string, and rosetta changes. Is that desired?

**Comment by ariel-phet** [comment]
@jonathanolson no...not currently desired. Though we might need to revisit if we ever go away from the "trusted" translator model.

**Comment by ariel-phet** [comment]
and thanks for the explanation, it seems for the moment we can count on people not being nefarious

**Comment by pixelzoom** [comment]
In the Java version of Translation Utility, translated strings are required to have the same number of placeholders (eg {0}) as the English string.  Otherwise the translated string is visibly flagged as an error, and the translation cannot be submitted.  I recall some previous discussion (with Aaron?) about this feature being added to Rosetta, but don't know if that was done.  Perhaps @jbphet can verify, or someone can try it in Rosetta.

**Comment by pixelzoom** [comment]
Rosetta enforces patterns:

![screenshot_16](https://cloud.githubusercontent.com/assets/3046552/13156242/c10d0062-d63e-11e5-8004-a3cc291f6c53.png)

**Comment by pixelzoom** [comment]
General issue of preventing Submit for a translation with errors is moved to https://github.com/phetsims/rosetta/issues/122.

Closing.
