### ISSUE TITLE
PhetMenu memory leak

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#327]
See https://github.com/phetsims/tasks/issues/546

**Comment by samreid** [comment]
I made changes in the phet-menu branch that eagerly create the PhET Menu once per PhETButton instead of lazily and repeatedly.  Testing with fuzzMouse=100 over 60 seconds, I see:

master: 16.8MB -> 72.2MB
phet-menu: 13.5MB -> 14.4MB

So it seems this has addressed the majority of the problem, though there is still likely an issue somewhere.

This seems like a good change, but it will need broad testing, perhaps at the next RC which uses latest joist, and a code review before merging to master.  @jbphet could you take a look?

**Comment by samreid** [comment]
Also pinging @ariel-phet about testing this, we could either (a) create a test just for testing the phet button + phet menu on every platform or (b) bundle this test into some upcoming RC.

**Comment by ariel-phet** [comment]
Seems worth bundling into an upcoming RC

**Comment by jbphet** [comment]
The changes look reasonable, and I tested them by switching joist to the branch and running a sim (Balancing Act) and popping up the menu several times, taking heap snapshots as I went.  The number of allocated PhetMenus stayed constant at 2.  I believe that it's because there is one for the home screen and one for the nav bar.  I also ran Hooke's Law using the ```fuzzMouse=100``` with this change in place, and took periodic heap snapshots as I did in https://github.com/phetsims/tasks/issues/546, and the memory increased much more slowly.  For two specific data points, the memory was at 27.1 MB vs 39.6 MB at 30 seconds and 28.0 vs 52.3 MB at 1 minute.

In the course of testing this I found leaks for the dialog windows brought up by PhetMenu, but I'll log those in another issue.  I think this one can be closed.

**Comment by samreid** [comment]
> I believe that it's because there is one for the home screen and one for the nav bar. 

Yes, that's right.

**Comment by jbphet** [comment]
Reopening - I should have assigned back to @samreid for integration into master.

**Comment by samreid** [comment]
Merged into master and `phet-menu` branch deleted.
