### ISSUE TITLE
iPad screenshot feature with no other tabs open

### ISSUE THREAD

**Issue by phet-steele** [phetsims/joist#333]
Since sims are technically "bigger" running on an iPad with no tabs open (see #234), the resulting screenshot is...hard to explain, see below. Having a second tab open beforehand so the sim loads with the correct size results in a totally fine screenshot. For phetsims/tasks/issues/556.

Screenshot with no tabs open first, it appears cropped:
![20160421_163904](https://cloud.githubusercontent.com/assets/5863899/14726454/b26ce734-07df-11e6-8269-97a2abb8e6e0.jpg)

But really the image appears just slightly zoomed in. Same image zoomed out:
![20160421_163916](https://cloud.githubusercontent.com/assets/5863899/14726458/b60daa9a-07df-11e6-9116-3d45822808cc.jpg)

**Comment by pixelzoom** [comment]
@ariel-phet your call on this one.

**Comment by ariel-phet** [comment]
I am guessing that for most users, taking a screenshot on the iPad is by far more easily accomplished with the normal "Home + Wake/Sleep" button press.

It is unclear to me if the built in screenshot feature is getting used much on iPad, so I am willing to punt on this for the moment, or until we get a bug report from a user.

**Comment by samreid** [comment]
I tested the recent CCK RC on iPad 7, and saw much better behavior.  I took a screenshot with no other tabs:

![IMG_7595948DB809-1](https://user-images.githubusercontent.com/679486/107976739-438c6d80-6f77-11eb-814c-d2c64640f03d.jpeg)

And when I used the PhET menu "screenshot" feature, it showed at a nice size:

![IMG_5C7DA257C6CF-1](https://user-images.githubusercontent.com/679486/107976803-63bc2c80-6f77-11eb-84db-59229a9e4618.jpeg)

Perhaps that's because iPad image viewer got smarter and now knows to scale the image so it is fully visible.  I recommend closing this issue.
