### ISSUE TITLE
Should the AboutDialog be persistent?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#390]
Every time "About..." is pressed, it creates as new AboutDialog:

```js
      //About dialog button
      {
        text: menuItemAboutString,
        present: true,
        separatorBefore: isPhETBrand,
        callback: function() {
          new AboutDialog( sim.name, sim.version, sim.credits, Brand, sim.locale ).show();
        },
        tandem: tandem.createTandem( 'aboutButton' )
      }
```

This led to issues in a recent phet-io issue in which we had to dispose all the subcomponents of the about dialog when MultiLineText started requiring tandems.

@zepumph and I were wondering if it would be better to make the AboutDialog persistent (created on first display, then hidden & re-shown in subsequent displays) so that we don't have to deal with disposing it properly.  We were uncertain whether AboutDialog could handle window size changes elegantly (and hence favoring the strategy of creating a new one dynamically each time).

@pixelzoom any preference between (a) disposing AboutDialog and all its subcomponents recursively vs (b) making the AboutDialog persistent?

**Comment by pixelzoom** [comment]
The About dialog certainly shouldn't be _created_ until it's needed.  In general, arguments for making something persistent are: (a) it takes a significant amount of time to create, and (b) it's used repeatedly -- and I doubt that either of those is the case forAbout dialog. So unless there's some huge effort involved, I'm don't think that "so that we don't have to deal with disposing it properly" is a good reason for it to be persistent.

**Comment by samreid** [comment]
There is minimal up-front effort involved, and minor "maintenance effort" as new components are added to the AboutDialog.  Thanks for your thoughts, I'll reassign to @zepumph to make sure he has read through these concerns.  @zepumph let me know if you have any questions or comments, and feel free to close.
