### ISSUE TITLE
Factor out BarrierRectangle from Sim.js to a new file 

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#394]
This is to match the TBarrierRectangle, and to make the code easier to maintain.

**Comment by zepumph** [comment]
@pixelzoom thanks for your help in this. Would you mind looking over this change. Feel free to close it if looks good to you.

**Comment by pixelzoom** [comment]
I fixed a few things in the above commits, mostly documentation. There was 1 bug fixed in https://github.com/phetsims/joist/commit/7edb289ed9dec736b31d6746087e8f4a495d7632; if you called `BarrierRectangle` constructor without `options`, it would fail at `var tandem = options.tandem;`.  Review the above commits, and let me know if you have any questions.

There is still a latent bug.  If `BarrierRectangle` is called without `options.tandem`, then this line will fail:

```js
44     options.tandem = tandem.createSupertypeTandem();
```

My first instinct would be to change this to:

```js
44     options.tandem = tandem && tandem.createSupertypeTandem();
```

... but I'm not sure if that is correct.  I'm guessing that there's a pattern used to address this in other common code, but I don't know what that pattern is.  Perhaps @samreid can clarify.

**Comment by samreid** [comment]
Tandems for Joist should be passed through the required arguments.  The tandems will always be available (guaranteed to be created by Sim.js).

**Comment by pixelzoom** [comment]
Looking at MenuItem, I see:

```js
    options = _.extend( {
      tandem: Tandem.tandemRequired(),
      ...
    }, options );
```

Should that pattern be used here too? Or is MenuItem also using the wrong pattern?

**Comment by pixelzoom** [comment]
BarrierRectangle links to modalNodeStack, so `dispose` needs to be implemented.

**Comment by pixelzoom** [comment]
@samreid said:
> Tandems for Joist should be passed through the required arguments. The tandems will always be available (guaranteed to be created by Sim.js).

Disagree in this case. You've now made `BarrierRectangle` available to clients, and I could certainly see how I could use it for the keypad layer in Unit Rates.  So `tandem` should be an option, not a required constructor parameter.

**Comment by pixelzoom** [comment]
Additional problems noted in the TODO items that I added to code in above commit.

**Comment by samreid** [comment]
I agreed with @pixelzoom's recommendations and would add:

- [ ] Let's try implementing this with Plane instead of Rectangle. This could simplify the API and get rid of the resizing logic in Sim.resize.
- [ ] This default cornerRadius is already 0, so this option override is unnecessary:

```js
    options = _.extend( {
      cornerRadius: 0
    }, options );
```

- [ ] For `//TODO #394 implement dispose or document why unlink is unnecessary` currently BarrierRectangle is only used by Sim.js for the life of the sim and hence is never disposed.  When we rewrite dialogs to use BarrierRectangle, they may need to properly implement dispose.

- [ ] The code comment should extend to 120 chars instead of being wrapped at 75 chars.

After you address the issues raised by @pixelzoom in the review comments and the checkboxes above, we can take another look.

**Comment by samreid** [comment]
I removed the "priority low" label, but this does not need to be done before next week.

**Comment by zepumph** [comment]
@samreid I went with @pixelzoom's suggestion to keep tandem in the options for this one, and I implemented the dispose function even though it isn't used yet, just so it's there. Would one of you take another look? I'll assign both of you just so all are aware of the changes. 

In MenuItem I made tandem a required argument. No matter what we choose, I think that it should be consistent across these new files.

**Comment by pixelzoom** [comment]
Regarding whether to provide the tandem via a constructor parameter or option... If you're instrumenting a piece of common code that is used _exclusively_ by other common code that is also instrumented, then the tandem can be a required argument.  But if you're instrumenting a piece of code that is used (or potentially usable) by client code, then the tandem must be an option. 

For example, `joist.HomeScreen` is used only by code that is instrumented, so it's reasonable to have a `tandem` constructor parameter.  `sun.RectangularPushButton` is used by instrumented and un-instrumented code, so it requires a `tandem` option.

As I argued in https://github.com/phetsims/joist/issues/394#issuecomment-278718422... The factoring out of `BarrierRectangle` produced something that is potentially usable by uninstrumented client code, so `tandem` should be an option. (And  should it move to scenery-phet?)

In my quick glance at `MenuItem`(https://github.com/phetsims/joist/issues/393) ... It has no dependencies on other joist code, and looks like it could be generally useful to client.   So perhaps it should move to sun, and `tandem` should be an option.

**Comment by zepumph** [comment]
I fully agree with you, all great thoughts. For MenuItem I will move it to sun and tandem will be an option.

I will move Barrier Rectangle to scenery-phet ( I have no idea/opinion about why these two would be in separate repos, but it's easy to move, so we will just go ahead and start there. I will also make the tandem an option.

@pixelzoom thank you so kindly for all of your guidance.

**Comment by zepumph** [comment]
@pixelzoom would you mind taking a final look at this and closing if you think that all is good?

**Comment by pixelzoom** [comment]
Minor formatting issues, fixed in above commit. Otherwise looks good. Closing.

**Comment by pixelzoom** [comment]
Reopening. I noticed that visibility annotations were missing, fixed in above commit. @zepumph feel free to close after reviewing.
