### ISSUE TITLE
"Check for Updates..." color doesn't change when sim is out of date

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#396]
"Check for Updates..." in the PhET Menu is supposed to turn green when the sim is out of date:

```js
color: UpdateCheck.stateProperty.value === 'out-of-date' ? '#0a0' : '#000',
```

But that isn't happening:
![capture2](https://cloud.githubusercontent.com/assets/6396244/21942687/4ab701e6-d98b-11e6-8625-b4d90af4cb0a.PNG)

**Comment by jonathanolson** [comment]
It looks like the PhetMenu isn't reconstructed each time it's opened, so that probably caused the break.

Using a DerivedProperty for the color might be a clean solution, as long as the color is being directly passed as a fill/stroke.

**Comment by jessegreenberg** [comment]
Good idea @jonathanolson, that seems to work nicely.  Would you mind reviewing?

**Comment by jonathanolson** [comment]
I was thinking more along the line of my above commit, since you can pass a ```Property<string>``` or ```Property<Color>``` directly to a Node's fill/stroke.

That removes the need for the client-side update listener and disposal.

Additionally, the black default was duplicated, so I removed the one outside the options object handling.

@jessegreenberg can you review my commit above?

**Comment by jessegreenberg** [comment]
Much better @jonathanolson, thanks.  I forgot that ```Property.<string|Color>``` is a valid type for setFill(). I also verified that it is working correctly.  Closing.
