### ISSUE TITLE
Home screen requires 2 clicks for non-selected screen

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#433]
I know we have been using the current implementation of the homescreen for a while now and as far as I know, no problems have been reported.  Still, I noticed a potential for improvement and wanted to raise it for discussion.

Launching 1st screen after starting the sim:
1. Launch sim
2. Click on the 1st screen icon = > it launches right away

Launching 2nd screen after starting the sim:
1. Launch sim
2. Click on 2nd screen => the icon gets larger
3. Click on 2nd screen again => now it launches

Also, when using the navigation bar, it only takes one click to go to a screen.  Hence it seems asymmetrical to require 2 clicks from the home screen.  If the user clicks on the 2nd screen icon, it seems likely they want to launch the 2nd screen rather than see an enlarged icon for the 2nd screen and have to click it again.

Now that the rest of our UX is stabilized and streamlined, I think it would be good to revisit this particular aspect.  @ariel-phet can you comment on the original reason for this extra click, and whether you think it is still providing value?

**Comment by ariel-phet** [comment]
@samreid the home screen is set up to be scaffolded, with the design set up to be driving the user towards the first screen. 

The reason for this extra click was since the other homescreen icons are small and faded, the user could click on these to see what each screen is more clearly. This UX has served us well in interviews, so I do think it is still providing us value (with new users mostly going to the first screen). I do not see the navbar as asymmetric since once you have entered the sim, the goal of the navbar is to allow the quick movement back and forth between screens. So for new users of PhET I think this UX is still important, and experienced users (like myself) have no trouble with a quick double tap to go to a different screen from the start.

Closing, feel free to reopen if you feel this needs further discussion.
