### ISSUE TITLE
?showHomeScreenProperty shows up in instance proxies for single screen sims

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#466]
And edge case from https://github.com/phetsims/joist/issues/451. It looks like the `showHomeScreenProperty` can manipulate faradays-law in unexpected and weird ways. 

In instance proxies, you can toggle that property directly, see here:
![image](https://user-images.githubusercontent.com/6856943/33101882-abeca016-cec6-11e7-954e-2ad3582fe7f9.png)

@samreid I'm tempted to just make this a phetioReadOnly Property, but I wanted to check in with you since you implemented it. Maybe this is revealing a deeper issue in the implementation.

**Comment by zepumph** [comment]
This is part of our effort in https://github.com/phetsims/joist/issues/445

**Comment by samreid** [comment]
It seems that `showHomeScreenProperty` shouldn't be instrumented for single screen sims.

**Comment by samreid** [comment]
Proposed fix is above, @zepumph can you please take a look?

**Comment by zepumph** [comment]
Looks good to me, thanks

**Comment by zepumph** [comment]
I'm no

**Comment by samreid** [comment]
Often code is simpler to follow if there is one point of assignment (so the variable doesn't spend any time with the wrong value), so I tend to recommend `var x = test ? A : B` rather than `var x = A; if (test) x=B`.  Of course there are counterexamples where the latter is simpler (depending on the nature of the test).  Can I reassign to you to try that strategy out for cases like https://github.com/phetsims/joist/issues/466#issuecomment-346446017 ?

**Comment by zepumph** [comment]
Sounds good. Thanks @samreid.
