### ISSUE TITLE
Common `speed` query parameter

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#476]
Equality Explorer has basically the exact query parameter I was hoping to see in other simulations. Discussed briefly in slack, and I'm going to move it to be a query parameter for all sims.

**Comment by jonathanolson** [comment]
There were no other namespace collisions. phet-io playback wrapper has a query parameter named `speed` also, but they will not be used in the same contexts (confirmed with @zepumph).

@pixelzoom, I believe I refactored it out (and tested to make sure it was working still for your sim), but let me know if I messed anything up. Feel free to close if everything is fine.

**Comment by pixelzoom** [comment]
EqEx looks good, no problem -- thanks for taking care of that.   

I asked @jonathanolson "What are intended uses?"  Slack discussion from there:

> Jonathan Olson [6:18 PM]
Main intended uses were for internal "see how the animation looks slowed down" (for design, since they were hard to see), and for QA (as many things are WAY easier to do when slowed down)
> 
> Chris Malley [6:18 PM]
Concerns about models/views that may blow up with extreme values?
I’ve used it exclusively for development and QA.
> 
> Jonathan Olson [6:19 PM]
Not concerned about extreme values. If that was the case, we would also have discussed minimum DTs

I also have a minor concern about whether I should go back and modify (or at least test) sims that have a similar query parameter.  Think I'll create sim-specific issue for each sim that has a similar query parameter.

**Comment by pixelzoom** [comment]
Reopening.  

This was supposed to affect animation.  But it's affecting anything that uses phet-core Timer.   For example, with `?speed=0.1`, the "continuous fire" feature of NumberPicker become unresponsive.

**Comment by pixelzoom** [comment]
Since this is intended to be a debug/test query parameter, I could live with NumberPicker becoming unresponsive -- though it's very inconvenient.   But I wonder what else might be affected.

**Comment by pixelzoom** [comment]
I addressed this by revising the documentation for 'speed' -- which had some other copy-paste errors, since it was apparently copied directly from Equality Explorer without changes.  See https://github.com/phetsims/chipper/commit/489c7ec58add96bd6ee8e37f29901a6f5f126cf2.

Closing.
