### ISSUE TITLE
bottom part of dev bounds are chopped off on home screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#541]
Reported for Graphing Quadratics in https://github.com/phetsims/graphing-quadratics/issues/121, but affects all sims.  

The bottom part of the dev bounds rectangle is chopped off in master.  Compare Equality Explorer in master (top) vs published (bottom):

![screenshot_911](https://user-images.githubusercontent.com/3046552/49397215-34070e00-f6f8-11e8-851b-e060f086b73b.png) 
![screenshot_912](https://user-images.githubusercontent.com/3046552/49397210-31a4b400-f6f8-11e8-9ebc-4f82f800336e.png)

**Comment by pixelzoom** [comment]
@jonathanolson FYI, since your RC for the Fractions suite contains this problem.

**Comment by samreid** [comment]
Issue https://github.com/phetsims/joist/issues/503 has commit 088058b6dd9b526384d87c9857107304a30ba155 which says: 

> Nav bar shows on home screen

Maybe that is obscuring the dev bounds?

**Comment by pixelzoom** [comment]
Looking through commits on `HomeScreenView`, I'm betting that this was caused by adding sound and keyboard icons to the home screen in https://github.com/phetsims/joist/issues/503.  @chrisklus @jbphet is that possible?

**Comment by jonathanolson** [comment]
This doesn't seem like an issue worth patching for RCs/published sims. Presumably `?dev` is for internal use?

**Comment by chrisklus** [comment]
>I'm betting that this was caused by adding sound and keyboard icons to the home screen in #503. @chrisklus @jbphet is that possible?

@pixelzoom at first glance of https://github.com/phetsims/joist/issues/541#issue-386973885, that seems likely. We are checking.

**Comment by samreid** [comment]
The home screen dev bounds is also shifted down (compared to the dev bounds on each screen).

**Comment by pixelzoom** [comment]
@jonathanolson said:
> This doesn't seem like an issue worth patching for RCs/published sims. Presumably ?dev is for internal use

@jonathanolson up to you, just wanted you to be in the loop.

**Comment by jbphet** [comment]
I just tested this on tambo, since it is a multi-screen sim with both sound and keyboard accessibility permanently turned on, and I'm seeing that the dev bounds on the home screen are also wider than those of the other screens.

On the screens, the dev bounds are above the nav bar, so it sort of looks to me like we added the nav bar but didn't adjust the dev bounds to accommodate it.  We will continue to investigate.

For what it's worth, I agree that this wouldn't be worth a patch.

**Comment by pixelzoom** [comment]
I'm going to ignore this for Graphing Quadratics 1.0, based on the consensus that this doesn't affect anything other than the internal `dev` query parameter.  If that changes, please notify me.

Slack:

> Chris Malley [1:09 PM]
Is there anything here that you feel needs to be corrected in the 1.0 release branch of Graphing Quadratics?
> 
> John Blanco [1:10 PM]
So far I'd say no, since this is a developer-only feature, but we will keep you posted as to whether it reveals any larger issue.

**Comment by chrisklus** [comment]
@samreid and I investigated this for a bit and found that if we change line 126 in Sim.js from
```js
self.homeScreen && self.homeScreen.view.layout( width, height );
```

to 

```js
self.homeScreen && self.homeScreen.view.layout( width, screenHeight );
```
which is the same way that the screens are laid out, then the bottom border of the dev bound appears above the nav bar so the whole rectangle is in view.

![image](https://user-images.githubusercontent.com/5618316/49407290-3c217680-f715-11e8-8462-26de8143793a.png)


![image](https://user-images.githubusercontent.com/5618316/49407239-1dbb7b00-f715-11e8-9aa9-7546229a5aa1.png)

A difference with this change is that the aspect ratio of the home screen is maintained, so the title and home screen icons are a little smaller. They are also a little higher up, since the home screen contents are positioned in the y-direction between the top of the window and the top of the nav bar instead of the top and bottom of the window.

Some options:

1. Do nothing and leave the dev bounds extended behind the nav bar on the home screen.
2. Commit the above change so that the dev bounds look correct but everything on the home screen is slightly smaller and positioned a little higher.
3. Commit the above change so that the dev bounds are correct and compensate for the changes in position in size so that everything on the home screen appears as it currently does. @samreid and I started down this path but felt that it was going to get a little tricky.


We were thinking this is a decision that @ariel-phet or another designer should give some input on.

**Comment by pixelzoom** [comment]
> 2. Commit the above change so that the dev bounds look correct but everything on the home screen is slightly smaller and positioned a little higher.

I don't think we should do anything that changes the size or position of the home screen icons.

**Comment by ariel-phet** [comment]
Removing status:blocks-publication

**Comment by samreid** [comment]
To clarify on point (3) from https://github.com/phetsims/joist/issues/541#issuecomment-443910753, it would be relatively easy (an hour or so) to match the location and size of the home screen at the default resolution (when the simulation is exactly at our prescribed aspect ratio), but the behavior would differ from master as the window is reshaped.

**Comment by pixelzoom** [comment]
If the home screen now needs a navigation bar, why not change the implementation so that it's like the other screens?  And the dev bounds would then stroke the ScreenView's layoutBounds, not the entire home screen.

**Comment by samreid** [comment]
That sounds great to me, and I recommend we do so.  The only caveat is that we won't be able to exactly match the prior scaling behavior (though we will be able to match how it looks at the default aspect ratio).

**Comment by pixelzoom** [comment]
I think it would be fine (and in fact preferable) if the contents of the home screen scaled up/down in the same way as the contents of all other screens.

**Comment by jbphet** [comment]
Scaling of the home screen that is consistent with the other screens also seems good to me, and the consistency may make the code easier to maintain.

**Comment by samreid** [comment]
We heard from two developers, which is good!  But it would also be nice to hear from a designer, particularly about whether it is OK to have a different scaling algorithm than we have had previously.  To be specific, we can set up so that the home screen so that at the default aspect ratio it looks the same as it does now, and at different aspect ratios, it would scale like sim screens do (which is not how home screen currently behaves--because home screen currently lays out on the entire screen, not the area above the navigation bar).  It's a minor distinction, but @chrisklus and I would like a designer to sign off on this before we begin.

**Comment by ariel-phet** [comment]
@samreid @chrisklus this designer is signing off that this alternative scaling would be fine. Now that we are out of the January woods might be a good time to polish this work off in the next month or so.

Marking medium priority

**Comment by samreid** [comment]
Here's a solution that matches the layout for the default aspect ration or thinner.  For wider than the default aspect ratio, the old layout scales more because it had more vertical space to fill out.

```
Index: js/HomeScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/HomeScreenView.js	(revision 4c32aa25129b23ca7ed5a8de7801894adf2eb76a)
+++ js/HomeScreenView.js	(date 1554267389000)
@@ -64,7 +64,7 @@
         family: TITLE_FONT_FAMILY
       } ),
       fill: 'white',
-      y: 110,
+      y: 130,
       tandem: tandem.createTandem( 'title' )
     } );
     this.addChild( title );
@@ -201,7 +201,7 @@
 
       // position the icons
       iconsParentNode.centerX = self.layoutBounds.width / 2;
-      iconsParentNode.top = self.layoutBounds.height / 3;
+      iconsParentNode.top = self.layoutBounds.height / 3 + 20;
     } );
 
     if ( options.warningNode ) {
@@ -209,7 +209,7 @@
 
       this.addChild( warningNode );
       warningNode.centerX = this.layoutBounds.centerX;
-      warningNode.bottom = this.layoutBounds.maxY - 20;
+      warningNode.bottom = this.layoutBounds.maxY - 2;
     }
   }
 
Index: js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/Sim.js	(revision 4c32aa25129b23ca7ed5a8de7801894adf2eb76a)
+++ js/Sim.js	(date 1554267389000)
@@ -124,7 +124,7 @@
 
         // Resize the layer with all of the dialogs, etc.
         self.topLayer.setScaleMagnitude( scale );
-        self.homeScreen && self.homeScreen.view.layout( width, height );
+        self.homeScreen && self.homeScreen.view.layout( width, screenHeight );
 
         // Fixes problems where the div would be way off center on iOS7
         if ( platform.mobileSafari ) {

```

I didn't commit this because it is not exactly the strategy proposed in https://github.com/phetsims/joist/issues/541#issuecomment-444164682 about actually adding the navigation bar to the home screen.  But I'm not sure we actually want the navigation bar on the home page, because we don't want to show the title, home icon, screen icons.  Not sure about sound or accessibility icons.  @jessegreenberg or @zepumph can you comment?

**Comment by samreid** [comment]
I checked tambo, and noted that the sound and keyboard icons are visible on the homescreen even though there is no navigation bar there.

Therefore, I recommend that we commit the proposal from https://github.com/phetsims/joist/issues/541#issuecomment-479340327 and mark as blocks-publication until that's been reviewed.  That is a minimal change that addresses the problem raised by this issue.  Then we can open another issue to investigate and determine whether we should use an actual navigation bar (without title or screen buttons) on the home screen.

**Comment by chrisklus** [comment]
@samreid and I reviewed his committed change from above, and found that the home screen scaling is identical to the previous home screen when window size of the sims aspect ratio is used, and when the layout is constrained in the x-direction. When the layout is constrained in the y direction (short and wide view), the scaling matches sim screen behavior instead of the previous home screen.

We also noticed that before the dev bounds didn't go behind the nav bar, a warning in molecule shapes was covered up by the nav bar, but now it's visible.
![image](https://user-images.githubusercontent.com/5618316/55648124-b2ee7f00-579c-11e9-9e4c-cc3d7785b58f.png)

![image](https://user-images.githubusercontent.com/5618316/55648335-458f1e00-579d-11e9-9ed5-b0850a12ee64.png)

Since this rescaling was approved in https://github.com/phetsims/joist/issues/541#issuecomment-459447868, and @samreid and I think it looks good, we are going to close.
