### ISSUE TITLE
global sound button doesn't work with state wrapper

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#547]
I have done no investigation on this, so perhaps all that needs to happen is an instrumentation, but I wanted to document it before forgetting,
![image](https://user-images.githubusercontent.com/6856943/50532124-3d01ba00-0ac1-11e9-85a8-13371aa2ecb8.png)

**Comment by zepumph** [comment]
Instrumented above, @jbphet can you please review. Does this look alright to you?

**Comment by jbphet** [comment]
For the most part, it looks reasonable to me.  I do have one question.  I noticed that the name of the property was changed from `enabledProperty` to `soundEnabledProperty`.  Since the property was owned by the `soundManager` singleton, I had thought that `enabledProperty` was clear enough in that context.  Was the "sound" portion prepended because the tandem won't have the context of knowing that it's part of the sound manager?  It's not a big deal to me either way, but if the tandem is going to be something like`...soundManager.soundEnabledProperty`, it strikes me as unnecessarily verbose to have "sound" in there twice.

**Comment by zepumph** [comment]
>Was the "sound" portion prepended because the tandem won't have the context of knowing that it's part of the sound manager?

Yes that was my thinking. I think there are two ways to go, keeping in mind that it is convention for the tandem name to match exactly the variable name.

1. The implementation I did, renaming the const only to match the tandem name (I too thought that your naming was just fine for your purposes).
2. Instrument, at least in name, the soundManager such that the tandem looks more like the code: `friction.general.soundManager.enabledProperty`.

The second seemed slightly worse to me for the job at hand, though I may feel differently if soon there are 10 things on soundManager that need instrumentation. If you agree please close, otherwise we can discuss further solutions. Also tagging @samreid in case he has an opinion about the name of this general phetioID.

**Comment by samreid** [comment]
`friction.general.soundManager.enabledProperty` sounds more like the sound manager is enabled.  `friction.general.soundManager.soundEnabledProperty` sounds more like the sound is enabled.  In the absence of further information, I'd lean toward the latter.

**Comment by jbphet** [comment]
Okay, I'm convinced.  Closing.

**Comment by zepumph** [comment]
Just making sure that @samreid is on the same page, since what we actually went with is `friction.general.soundEnabledProperty`, see https://github.com/phetsims/tambo/commit/9e7de6ceff5c4809706452fcd062a06020e97ebb.

@samreid please close if all looks alright.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
