### ISSUE TITLE
PhET-iO instrumentation of PhET menu

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#554]
In https://github.com/phetsims/graphing-quadratics/issues/112 and https://docs.google.com/document/d/1OfHhIDuaBt-hhXVtpnJgM3Wm0iByJ7dmXd-2UkphUR4/edit#, the Navigation section has requirements related to the PhET menu.  This section applies to all sims and needs more discussion.

Here's what it looked like on 2/2/28:

<img width="736" alt="screenshot_1094" src="https://user-images.githubusercontent.com/3046552/53600622-3813c200-3b67-11e9-9e9b-11612be3db57.png">

**Comment by samreid** [comment]
From today's phet-io design meeting: @kathy-phet said we would like to solidify the about dialog and phet menu.  @kathy-phet and @arouinfar will review this together with https://github.com/phetsims/phet-io/issues/1586

**Comment by arouinfar** [comment]
@kathy-phet and I reviewed the phetMenu and aboutDialog in studio.

* `phetMenu.enhancedSoundMenuItem.visibleProperty` should be featured.
* There are five menuItems under the phetMenu which appear in the tree, regardless of whether or not they are relevant to the particular sim. Not all sims have an Options menu or Enhanced Sound. It's a bit problematic to have these irrelevant menuItems in the tree, since all they all have their visibleProperty featured. Users may encounter something featured that doesn't actually exist in the sim.  It would be preferable to exclude irrelevant menuItems from the tree.  
* Now that `?allowLinks=false` is up and running, do we need the links in the about menu instrumented at all?  @kathy-phet mentioned it might be more maintainable if the links are uninstrumented in case we decide to make changes later on (like splitting Terms & Licensing into separate links). If the links really do need to be instrumented, then all of their properties should be read only and `aboutDialogCapsule.archetype.termsPrivacyAndLicensingText` should be renamed `aboutDialogCapsule.archetype.termsPrivacyAndLicensingLinkText` so its name is parallel to the other LinkText siblings. 
* It seems a bit odd that `phetMenu.aboutDialogCapsule` and `phetMenu.aboutMenuItem` are siblings. We thought it might be more natural for the aboutDialogCapsule to be nested under the aboutMenuItem, but the current structure is still okay with us if it makes more sense in the code.

**Comment by arouinfar** [comment]
Assigning to @zepumph, but please reassign to another dev if appropriate.

**Comment by zepumph** [comment]
> There are five menuItems under the phetMenu which appear in the tree, regardless of whether or not they are relevant to the particular sim. Not all sims have an Options menu or Enhanced Sound. It's a bit problematic to have these irrelevant menuItems in the tree, since all they all have their visibleProperty featured. Users may encounter something featured that doesn't actually exist in the sim. It would be preferable to exclude irrelevant menuItems from the tree.

This is largely being worked on as part of https://github.com/phetsims/phet-io/issues/1457, but it will be good to link these two.

**Comment by chrisklus** [comment]
Items (1) and (3) from https://github.com/phetsims/joist/issues/554#issuecomment-578941025 are ready for review.

**Comment by arouinfar** [comment]
Looks good in master @chrisklus! Since the remaining work will be tracked in other issues, I'll go ahead and close.
