### ISSUE TITLE
stepSimulationAction doesn't do frameEndedEmitter.emit

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#561]
This seems very odd:

```js
function Sim(...) {
  ...
  // @public ...
  this.stepSimulationAction = new Action( dt => {
    this.frameStartedEmitter.emit();
    ...
  } );
}
   
stepSimulation: function( dt ) {
  this.stepSimulationAction.execute( dt );
  this.frameEndedEmitter.emit();
},
```

Why aren't `frameStartedEmitter.emit()` and `frameEndedEmitter.emit()` both inside the function executed by `stepSimulationAction`?  This looks like a problem, especially since `stepSimulationAction` is public. If a client calls `stepSimulationAction.execute`, who handles `frameEndedEmitter.emit`?  Please explain and document.

**Comment by samreid** [comment]
I cannot recall whether this was intentional to support the playback wrapper (and will need to remain as it is), or if it is vestigially asymmetrical (and the `frameEndedEmitter` could be moved into the `Action`).  @zepumph do you know offhand, or shall we investigate?

**Comment by zepumph** [comment]
We converted the logic to use the action in https://github.com/phetsims/joist/commit/ccfd0c4ec8651d93d41c4d8dd7887429293abf3e#diff-1a1c3747494feba507339d0cc74ad5caL895.

Then it was swapped over to the stepSimulation call (instead of the action) in https://github.com/phetsims/joist/commit/c7b3da273f3813c7f7cef2d057dd78f65f5e8ee8.

This looks very safe to move over. Good find @pixelzoom. @pixelzoom please close if all looks good.

**Comment by pixelzoom** [comment]
👍 closing.
