### ISSUE TITLE
Homescreen cut off with long screen titles

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#60]
See BAM running with Hungarian:
![bam-hungarian-home-cutoff](https://f.cloud.github.com/assets/480878/1341413/e7f26cdc-3648-11e3-809b-5b43c30d68c8.PNG)

**Comment by samreid** [comment]
We should probably implement this before republishing any sims for i18n.  Reassigned to @jonathanolson @pixelzoom and/or @jbphet to make sure it is on their radar.

**Comment by pixelzoom** [comment]
This appears to have already been addressed. For example:

states-of-matter_en.html?dev&stringTest=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

![screenshot_518](https://cloud.githubusercontent.com/assets/3046552/7571071/329917f8-f7d2-11e4-8a9a-8c6aa0a12f8e.png)

@samreid It looks like you committed the fix for this. Did you have something else in mind for how this should work?

**Comment by samreid** [comment]
> @samreid It looks like you committed the fix for this. Did you have something else in mind for how this should work?

Ah, I guess this issue was just left open because of the suggestion in this comment: https://github.com/phetsims/joist/issues/60#issuecomment-31726343

> But one thought I wanted to consider is shrinking all of the text uniformly instead of just the offenders. Not sure what will look better.

To which @jonathanolson repsonded:

> Maybe seeing visual examples would help us determine what is best?

So I think the "high priority" part of this issue is complete since all of the text will be legible.  It is a supplemental design issue to decide whether all fonts for screen names should match size (I suspect good designers would say yes).

**Comment by pixelzoom** [comment]
@samreid wrote:
> It is a supplemental design issue to decide whether all fonts for screen names should match size (I suspect good designers would say yes).

I also suspect that good designers would say "yes".  And we should strive to have identical font sizes for English strings.  But I'm not convinced that's desirable for non-English strings.

So far, our approach for collections for things (e.g., radio buttons in a panel, screen titles,...) has been to scale them independently. See for example i18n of states-of-matter (run with '?stringsTest=double').  Scaling collections of related things uniformly is more work, and causes all related components to suffer because of >=1 string that may be too long.  In general, I feel that (for non-English strings) it's preferably to scale down just the things that are too long, rather than making everything suffer; presumably the translator will notice this when they test, and can adjust the problematic string(s).  And specific to the screen titles, I feel we should continue to scale them independently.

**Comment by samreid** [comment]
Since our precedent is for nonuniformly scaled strings (for non-English), I am ok to close this issue.  Still, in the future it may be interesting to discuss what work would be required to employ uniformly scaled strings.  Reassigning to @ariel-phet to see if he is OK with the design decisions here and to see if he wants to create an issue for investigating uniformly scaled strings in the future (even if the answer is ultimately "too expensive to implement).

**Comment by pixelzoom** [comment]
I'll put this on the agenda for discussion at developer meeting.

**Comment by pixelzoom** [comment]
At dev meeting, the consensus was that our current approach of scaling strings independently is best. 

Closing.
