### ISSUE TITLE
How to determine whether to select a subset of screens?

### ISSUE THREAD

**Issue by samreid** [phetsims/joist#614]
From #602, @jonathanolson said:

```js
  if ( screensQueryParameterProvided ) {
    //REVIEW: Shouldn't we just see if the result is the default value of `null`, instead of checking if it was
    //REVIEW: provided? See https://github.com/phetsims/joist/issues/602
```

@chrisklus and I discussed this and agree it would work properly and shorten the code to check for `null` instead of using `screensQueryParameterProvided`.  However, there is no robust way to check for the default value in the query parameter schema, so this would be somewhat brittle.  Also, we recommend using this pattern so that it is symmetrical with the other parameters where this pattern is necessary.  Or we could make it easier to access the query parameter schema defaults?  But that kind of functionality is already covered by `containsKey`.

@jonathanolson what do you think?

**Comment by chrisklus** [comment]
From working on https://github.com/phetsims/joist/issues/599:

Aside from the reasons @samreid mentioned above, it's not sufficient to just check if the value is `null` because QueryStringMachine is doing some validation on the value of `screens` (before the sim-specific validation happens at the place of this review comment in selectScreens.js). Since `screens` was marked as public in https://github.com/phetsims/joist/issues/599, if the user-provided value doesn't satisfy the isValidValue function from the schema in initialize-globals.js, then the value will be reverted to its default value (`null`) before it gets to Sim.js. So it's now possible that `screensQueryParameterProvided` can be true while `screensQueryParameter` is `null`.

I removed the review comment and am going to close and continue review/discussion in https://github.com/phetsims/joist/issues/599, anyone feel free to reopen or comment in https://github.com/phetsims/joist/issues/599 if you'd like to discuss more.
