### ISSUE TITLE
Enable zoom feature by default

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#657]
This was discussed during 8/27/20 status meeting as something we are ready to do. The feature has been published in one sim and we would like it in as many as possible.

Also referencing https://github.com/phetsims/aqua/issues/106 as something that can hopefully be finished shortly after this, as it would be nice to start testing this feature as part of CT now that it has wide use.

**Comment by jessegreenberg** [comment]
@pixelzoom - @ariel-phet mentioned you had a recommended improvement for the query parameter, assigning to you to comment.

**Comment by pixelzoom** [comment]
I was wondering why `supportsZoom` can't be 'boolean'. It seemed very odd that it's of type 'string'.  But I see that `null` means to use the default that's specified in package.json.  So I guess we can leave it as is, but it's going to make it challenging to explain this in the PhET-iO Client Guides.

**Comment by jessegreenberg** [comment]
Exactly, I wanted the query parameter to always take priority so that if `supportsZoom: true` in package.json, it could still be disabled with `?supportsZoom=false` query param. Or if disabled in package.json, you could still test it with `?supportsZoom=true`.

One thing we could do to make it boolean is this:
```
supportsZoom = packageJSON.phet.supportsZoom === undefined ? phet.chipper.queryParameters.supportsZoom : packageJSON.phet.supportsZoom;
```

This works better when zoom is enabled by default because the package.json entry will only be used to permanently disable zoom. But then `supportsZoom: true` in package.json and `?supportsZoom:=false` query param would still have zoom enabled.

Would that be better?

**Comment by pixelzoom** [comment]
How about this?

```js
    supportsZoom: {
      type: 'boolean',
      defaultValue: packageJSON.phet.supportsZoom
    }
```

**Comment by jessegreenberg** [comment]
That is very nice! I am not sure how to use packageJSON in initialize-globals yet though.

**Comment by pixelzoom** [comment]
Jesse Greenberg  3:30 PM
I also notice that the `window.phet.chipper.packageObject` is available in the IIFE on line 618 of initialize-globals. would accessing that way be better in this context?

Chris Malley  3:33 PM
Putting a `debugger` at the top of initialize-globals.js, it's defined when the IIFE is evaluated.

Jesse Greenberg  3:35 PM
OK cool, so `packageJSON = window.phet.chipper.packageObject` is sufficient?

Chris Malley  3:36 PM
So for initializing supportsZoom, this should work (untested)

```js
supportsZoom: {
  type: 'boolean',
  defaultValue: !!window.phet.chipper.packageObject.supportsZoom
}
```

**Comment by jessegreenberg** [comment]
OK, the zoom feature is now enabled by default. Instead of https://github.com/phetsims/joist/issues/657#issuecomment-686778830 I went with 
```js
    supportsZoom: {
      type: 'boolean',
      defaultValue: packageObject.phet.supportsZoom === undefined || packageObject.phet.supportsZoom,
      public: true
    }
```

because I wanted the default value to be true if there isn't an entry in package.json.

**Comment by jessegreenberg** [comment]
After running tests locally I noticed substantial problems in rutherford-scattering, density, buoyancy and I disabled the feature in those three sims until problems can be solved.

Otherwise, sims are running without error with `?fuzz&fuzzPointers=2` (other than the issues noted in https://github.com/phetsims/aqua/issues/106), unrelated to this feature.

I notified the general slack channel that this has been done for all sims on master. I will be watching CT for new issues related to this. Going to leave this open until we have a few iterations of CT looking OK.

**Comment by samreid** [comment]
```js
const packageObject = window.phet.chipper.packageObject;
```
is not defined for some scenery runtimes, and is hence failing on CT:

```
scenery : pageload : /tests/renderer-comparison.html?renderers=canvas,svg,dom
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599199242679/scenery/tests/renderer-comparison.html?renderers=canvas,svg,dom
Uncaught TypeError: Cannot read property 'chipper' of undefined
TypeError: Cannot read property 'chipper' of undefined
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599199242679/chipper/js/initialize-globals.js:37:37
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599199242679/chipper/js/initialize-globals.js:846:2
id: Bayes Chrome
Snapshot from 9/4/2020, 12:00:42 AM
```

**Comment by jessegreenberg** [comment]
> is not defined for some scenery runtimes, and is hence failing on CT:

I see, thank you! Fixed in https://github.com/phetsims/chipper/commit/fdb3a425c8d4fa397f2480c65c0fe605e152f540.

**Comment by jessegreenberg** [comment]
> Should we remove all of the "supportsZoom": true since that is now the default?

Yes indeed, thanks! Done in the following commits.

**Comment by pixelzoom** [comment]
In Slack, @jessegreenberg mentioned that zoom was causing problems in a few sims, possibly related to WebGL.  Natural Selection uses WebGL (see `OrganismSprites`).

Relevant Slack messages in general channel:

Jesse Greenberg  5:35 PM
Hello all. The zoom feature is now enabled in all PhET sims on master with the exceptions of rutherford-scattering, density, and buoyancy. These were the only sims where I noticed substantial problems.  ...

Jesse Greenberg  5:55 PM
I am seeing a similar issue from density/bouyancy in charges-and-fields so it looks like the issue might be caused by zoom with the use of WebGL. Ill take a look at that soon.

Chris Malley  8:46 PM
Hmmm. Natural Selection uses WebGL, so be on the lookout there too.

**Comment by pixelzoom** [comment]
@jessegreenberg What is the timeframe for investigating the problem with WebGL sims? Do you want to do that in this issue, or create a new issue?

FYI, Natural Selection uses WebGL. On 9/17, we start QA on a dev version that will be delivered to the client. Zoom can be disabled for the 9/17 deliverable (if necessary, but not optimal). But then we immediately begin QA for production versions, and I believe this needs to be resolved for that process.

@ariel-phet feel free to chime in with any clarification.

**Comment by pixelzoom** [comment]
Labeling blocks-sim-publication to remind me that Zoom needs to be either disabled or addressed for 10/1 deliverable.

**Comment by pixelzoom** [comment]
Slack PM with @jessegreenberg and @ariel-phet:

Chris Malley  2:10 PM
When you have a minute, could you both reply to https://github.com/phetsims/joist/issues/657#issuecomment-689048459? Thanks.

Ariel Paul  2:12 PM
Is the zoom feature causing an actual issue in NS? I know it uses webgl but does it do it in a way that is causing issues or is it just suspected that it might?

Chris Malley  2:13 PM
@jessegreenberg said "These were the only sims where I noticed substantial problems" but did not identify what the "substantial problems" were.  Due to the nature of NS, there are many things that CT does not test adequately.  So if there's a WebGL problem, CT might not find it.

Ariel Paul  2:14 PM
Right but NS was not in that list

Chris Malley  2:14 PM
Right, but @jessegreenberg said "the issue might be caused by zoom with the use of WebGL"

Jesse Greenberg  2:15 PM
I actually just finished a zoom call with JO abut this and he helped me verify that it is not a general problem with WebGL but a problem with the way a few sims are using WebGL.

Ariel Paul  2:15 PM
@jessegreenberg is NS such a sim?

Chris Malley  2:15 PM
What way of using WebGL causes the problem?

Jesse Greenberg  2:15 PM
The issue that I saw was just that the visuals of the WebGL node are not zooming with the rest of the sim. I did not see that in NS.
2:16
The problem is in the shader code, some shaders are not using the modelViewMatrix to transform the content (edited) 

Ariel Paul  2:17 PM
OK, that helps me make a comment, thanks

Chris Malley  2:17 PM
OK. NS is not doing anything explicitly with shaders. And I don't see anything related to shaders in Sprites.js (which what NS uses for WebGL), but I'll confirm with JO. (edited) 

Jesse Greenberg  2:17 PM
So we need to review the sims that are using WebGLNode and see what sims have this problem, then go through those and fix.

Chris Malley  2:18 PM
So the other question was: Would you like to do that in a new issue, or continue in https://github.com/phetsims/joist/issues/657?

Jesse Greenberg  2:19 PM
Thanks, I am going to write up a new issue for that now

Chris Malley  2:19 PM
Sounds good. I'll capture this in https://github.com/phetsims/joist/issues/657

**Comment by ariel-phet** [comment]
It sounds like zoom will likely not be an issue from a WebGL standpoint in NS after a slack conversation with @jessegreenberg.

@pixelzoom we should go with zoom enabled at first, but if we run into any significant issues, zoom can be disabled. Zoom does not *need* to be enabled for the production version. Although desired, it is not a requirement. Moving forward we would certainly like to have zoom available in as many production sims as possible, but again, not a requirement for the coming production release.

**Comment by jessegreenberg** [comment]
> Going to leave this open until we have a few iterations of CT looking OK.

Nothing reported on CT and we have a few specific issues to work on in response to this, so closing this issue.
