### ISSUE TITLE
Toggle switch or Sound for Voicing in preferences should be removed when only one audio feature is available

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#736]
Discussed at a recent design meeting, when only one feature under audio is enabled, the toggle switch for it should be removed because in that case the "Audio" toggle will be the only thing required to enable/disable all auditory output. There is no need to add or remove subcomponents under audio when there is only one.

**Comment by jessegreenberg** [comment]
I decided to proceed with this for Sound but not for Voicing. It is more complicated for Voicing because the toggle switch for Voicing shows/hides many other UI components to control voicing output. And without the toggle switch for Voicing, we don't hear when the voicing output for "Voicing on/Voicing off" because it goes through auditory output. 

It will be very rare that Voicing is supported but sound is not. This will generally only happen when requested with query parameter. As such, I don't feel like this case needs to be as polished. But Ill be happy to work on this again if it is ever requested.

**Comment by zepumph** [comment]
Over in Number Play we are findin gthat this solution is incomplete because it assumes that the only sound in the project is Voicing and Sound, but we need this toggle on because we have SpeechSynthesis (not voicing). @chrisklus and I are going to create a new audio preferences model flag here called `supportsSpeechSynthesis` to indicate to preferences that some non-sound feature still exists even though Voicing doesn't.

**Comment by zepumph** [comment]
Nevermind, it is way way too hardcoded in joist that "audio" means sound and or voicing, and that's it. So we are going to bail here. Re-closing.
