### ISSUE TITLE
Text is bolder in screenshots than in the original sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/joist#742]
**Test device**
MacBook Air (m1 chip) and iMac

**Operating System**
11.4 and 10.15.7

**Browser**
Safari and chrome

**Problem description**
https://github.com/phetsims/qa/issues/692

This is more of an FYI-- when taking screenshots in the Screenshot Wrapper, the text in the screenshot appears bolder than in the original. Everything else is the same aside from that. I also noticed this happening when selecting the option in the PhET menu in the sim. 
This did not happen using a chromebook. Nor did it occur with mac + firefox. 

**Visuals**
All of the equations in the graph area are bolder. The differences are most obvious in the Quadratic Terms accordion box. 

Sim:
<img width="871" alt="Screen Shot 2021-08-20 at 10 06 53 AM" src="https://user-images.githubusercontent.com/87318828/130257434-a0bb1389-e696-4656-add8-92e544391bae.png">

Screenshot:
<img width="871" alt="Screen Shot 2021-08-20 at 10 07 10 AM" src="https://user-images.githubusercontent.com/87318828/130257479-98a1ebb9-b659-4833-9235-639fb1f381d0.png">

**Comment by samreid** [comment]
@jonathanolson said the main difference is due to the rendering in canvas, which is slightly different.  This is to be expected.  If the renderer in the sim was canvas, it would look the same.

@samreid says the different probably wouldn't cause a problem in use.

@zepumph recommended closing the issue, as will-not-fix.
