### ISSUE TITLE
audioManager.js Properties need to be instrumented for PhET-iO.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#745]
Related to https://github.com/phetsims/joist/issues/724 ....

Nancy Salpepi  reported in Slack:
> Hi There! Quick Question…if I turn off the sound in Studio and then launch the sim, the sound is on. Is that correct behavior?

I noted that none of the Properties in the new audioManager.js have been instrumented for PhET-iO.  Therefore the state of sound cannot be saved and restored. That seems like an oversight, because soundManager.js is instrumented.

@zepumph asked me to create this issue, and assign to him with high priority.

**Comment by zepumph** [comment]
I did the initial instrumentation, in the same pattern as SoundManager, all that seems to be needed is the audioEnabledProperty, as the rest are DerivedProperties that should only be instrumented if they serve a purpose for PhET-iO. Over to @arouinfar to review something like `friction.general.view.audioManager.audioEnabledProperty` in studio.

**Comment by arouinfar** [comment]
@zepumph this generally seems fine and stateful. However, it does feel a bit odd.

There isn't a way to mute the sound from the tree. Does that mean there isn't a way to mute the sound with an API call? I suppose a client could use `general.view.audioManager.audioEnabledProperty`, but that permanently disables the sound and a user wouldn't be able to re-enable it.

The solution might be to direct clients to the `audio` query parameter if they wish to mute by default or permanently disable the sound. I included `audio` in [phet-io-guide.md](https://github.com/phetsims/phet-io-client-guides/blob/master/greenhouse-effect/phet-io-guide.md) for Greenhouse Effect, and it's something that I'll be adding to the template for future sims with audio.

There is precedent for directing clients to query parameters instead of customization through Studio (such as `screens`), so I don't think there's necessarily anything wrong with the way things are now.

What do you think @zepumph?

**Comment by zepumph** [comment]
>There isn't a way to mute the sound from the tree. 

I was able to do that by toggling `friction.general.view.audioManager.audioEnabledProperty`. Perhaps I don't understand though. Toggling that Property shuts off the sound as if you pressed the button on the nav bar.

> but that permanently disables the sound and a user wouldn't be able to re-enable it.

I don't understand, as long as the button isn't set to enabled: false, it is still controllable from the wrapper.

**Comment by arouinfar** [comment]
My bad @zepumph. I think I searched for `sound` in the tree so I was using `general.view.soundManager.enabledProperty` earlier. Using this property mutes the sim and also disables the button in the navbar. The sim cannot be un-muted from the navbar. It also doesn't seem to be affected by changes to `general.view.audioManager.audioEnabledProperty`. If audio is disabled, shouldn't sound be disabled? Do we need both an `audioManager` and a `soundManager`?  

On the flip side, `general.view.audioManager.audioEnabledProperty` does what I would expect - it mutes the sim as though the button in the navbar was pressed.

Currently, `soundManager.enabledProperty` and `soundManager.enhancedSoundEnabledProperty` are both featured. The latter seems likely to be eliminated with changes in #744 since Enhanced Sound is an option in the Preferences dialog. It's also not clear to me if `soundManager.enabledProperty` still serves a purpose. Regardless, I would unfeature both of these, and instead feature `audioManager.audioEnabledProperty`.

**Comment by zepumph** [comment]
> It also doesn't seem to be affected by changes to general.view.audioManager.audioEnabledProperty

Yes the Property value of soundManager.enabledProperty doesn't change, but sound being on or off does. This is because `soundManager.enabledProperty` is just one of the dependencies of if sound is playing. Note here how many stars have to align to get sound actually playing (see `const fullyEnabled . . .`)

https://github.com/phetsims/tambo/blob/98effa9c6a488ec3520c7884e61f493b7615d9fd/js/soundManager.js#L175-L197

I'll swap the featured implementation.

**Comment by zepumph** [comment]
Alright, updated above. Anything else for this issue?

**Comment by arouinfar** [comment]
Thanks @zepumph. Looks good in Studio. Not sure if the code needs to be reviewed too, so back to you.

**Comment by arouinfar** [comment]
It looks like the changes will need to be cherry-picked for https://github.com/phetsims/greenhouse-effect/issues/91

**Comment by zepumph** [comment]
Sounds great. To cherry pick, you just need https://github.com/phetsims/joist/commit/7f9fce34497d46ea70e59fce32698a952fb79c72 and https://github.com/phetsims/tambo/commit/099510590da295e3ac3a3522b4be7a8cd989b219

----------------------

https://github.com/phetsims/phet-io/commit/4fef32ee65251aea9ffeaa7a4aeda102a778741f is just updating API files

**Comment by jessegreenberg** [comment]
It looks like I will need https://github.com/phetsims/joist/commit/1563c92d77d7490b5f96051f69489bb721a514aa before https://github.com/phetsims/joist/commit/7f9fce34497d46ea70e59fce32698a952fb79c72, will add that one first.

**Comment by jessegreenberg** [comment]
Cherry picks done for https://github.com/phetsims/greenhouse-effect/issues/91, I think this can be closed based on the above comments.
