### ISSUE TITLE
It's easy to accidentally change a UI control when you zoom/pan.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#749]
For https://github.com/phetsims/fourier-making-waves/issues/178. Seen on iPad, but would likely be on any touch screen.

When zooming in or out using pinch to zoom on a touch screen, if a finger is in the the area to adjust waves, that movement takes precedence over zooming. This can lead to unintended adjustments and, if the area is big enough, make returning to normal size difficult.

https://user-images.githubusercontent.com/41024075/134955549-089c196c-f43c-4fe1-85aa-f99348ad9b3e.MP4

**Comment by KatieWoe** [comment]
I'd like to note that I did sometimes have some trouble panning away as well.

**Comment by jessegreenberg** [comment]
The behavior shown here makes sense to me from what is currently in master. Interaction with UI components always takes precedence over pan and zoom and I think that is a good rule of thumb. If the expectation and behavior were flipped from what is shown above so that one intended to control the sliders but instead the sim zoomed out it would also be confusing. And if pan/zoom took priority it would generally be problematic for multitouch. I am OK closing this.

@arouinfar back to you to close if you are still OK with this.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg, let's close.
