### ISSUE TITLE
Sim playback has issues when window.innerWidth/window.innerHeight is used

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/joist#768]
Discovered this as the source of https://github.com/phetsims/molecule-shapes/issues/195.

We'll add a lint rule to prevent this, and fix up usages to instead use `Sim.dimensionProperty`.

**Comment by jonathanolson** [comment]
@zepumph anything else to do here? All commits above.

**Comment by zepumph** [comment]
All looks great above. The only thing left is to ping @jbphet about https://github.com/phetsims/states-of-matter/commit/d4564f0e0b923cc34ffa5a00da0e6639b402f746. 

@jbphet, please note that that window.innerWidth/Height, are not supported by PhET-iO playback, so we created a Property in Sim.js that contains the values needed. We were able to reproduce the bugginess in the mirror-inputs wrapper in atomic interactions, though the stakes were pretty low. Now, when an atom zooms off screen, it is based on the sim dimensions instead of the window. Please close unless you have further questions.

**Comment by jbphet** [comment]
Thanks for the heads up.  No further questions your honor - closing.
