### ISSUE TITLE
Potential difficulties with splash screen rotation on iPad

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/joist#785]
For https://github.com/phetsims/qa/issues/778. Seen on iPadOS 14 Safari.

When rotating the iPad while loading a sim (https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.7/phet-io/ratio-and-proportion_all_phet-io.html?postMessageOnError&phetioStandalone was recorded and seemed worse then PhET brand during brief testing) the loading bar may be in the wrong location. This isn't necessarily unusual or different from before, but it seems a bit more likely to stay there until the sim loads. Once loaded the sim seems to be in the right position. The sim also loads quickly enough that it can be hard to determine if the the wrong position is really permanent.

https://user-images.githubusercontent.com/41024075/156049122-9a13bd4d-5767-41d3-b393-7ae6fe37eb53.MP4

**Comment by zepumph** [comment]
Thanks for the report. Even in that video it took me 5 or so runs to see what you were talking about with "be[ing] in the wrong location." 

@arouinfar, do you think this is an issue to solve? The bug is (if I understand correctly) that in the video, after rotating, the splash screen is more to the left until hidden.

**Comment by arouinfar** [comment]
@zepumph this looks like a minor edge-case to me and seems unlikely to cause any real issues. Unless there is some clear and quick solution, I don't think we need to do anything here.

**Comment by zepumph** [comment]
Ok thanks. I agree.
