### ISSUE TITLE
Problems with PhET-iO instrumentation of Options dialog.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#799]
I'm not sure what `optionsDialogCapsule.optionsDialog.visibleProperty` is supposed to do. But it's not doing what I'd expect it to do, and it doesn't behave like any other `visibleProperty` elements.

For example:

1. Run Geometric Optics in Studio.
2. Open the Options dialog via PhET > Options.
3. Close the Options dialog.
4. Problem 1: In Studio, navigate to `optionsDialog.visibleProperty`. You'll see that its value is true, while the dialog in not visible.
5. Problem 2: Change `optionsDialog.visibleProperty` to false. Then select PhET > Options, and note that the Options dialog does not open. 
6. Problem 3: Also note that `optionsDialog.isShowingProperty` is true and the Options dialog is definitely not "showing".

Lots of questions:

* What is `optionsDialog.visibleProperty` supposed to do? 
* Why does `optionsDialog.visibleProperty` not behave like other `visibleProperty` elements?
* Why is `optionsDialog.visibleProperty` even instrumented?
* If `optionsDialog.visibleProperty` needs to be instrumented, why is it not read-only?
* Why do we have both `isVisibleProperty` and `isShowingProperty`, aren't they semantically the same thing?
* Shouldn't `isVisibleProperty` and `isShowingProperty` have `phetioDocumentation`?

I'll start by assigning to @arouinfar for design, @jonathanolson (`isShowingProperty` is in Popupable) and @zepumph (he worked on Dialog `visiblePropertyOptions`).

Labeling this as blocking, because it affects all iO sims.

**Comment by jonathanolson** [comment]
I haven't looked in depth into this, but it seems like it might be similar to this:

1. Problem 1: Create a Rectangle node. It's visibleProperty is true, but it's not showing on the screen
2. Problem 2: Set it to visible:false and add it to the screenView. It's not showing on the screen (even though it's in the screenView)
3. Problem 3: The rectangle is a child of the screenView, but it's not showing on the screen

One seems likely to control the visibility, the other controls whether it's added as an ancestor of the Display's rootNode.

**Comment by arouinfar** [comment]
From a design perspective, I don't see a reason for `isVisibleProperty` to exist. It makes sense for the `visibleProperty` to control whether or not the dialog is open/visible. If that's not reasonable, and `isShowingProperty` needs to be in control, the `visibleProperty` should be read-only and un-featured to avoid confusion.

**Comment by zepumph** [comment]
`isShowingProperty` is part of the Popupable API. Though @pixelzoom is totally correct in his assessment of things, I'm not too keen to change how that works. Instead, like @arouinfar mentioned in https://github.com/phetsims/joist/issues/799#issuecomment-1090584134, I think it will be best to remove capabilities from Dialog's visibleProperty for PhET-iO to avoid confusion.

**Comment by zepumph** [comment]
So with this change both isShowingProperty and visibleProperty are readonly. Dialog is run on isShowingProperty. In general this makes sense because it doesn't make sense to control the visibility of a dialog with PhET-iO. Instead, we just control the element that toggles the dialog. So for the options dialog you just hide the menu item. This avoids the confusion that @pixelzoom mentioned in the original comment where you "open" the dialog but nothing shows up. 

Anything else here @arouinfar.

**Comment by arouinfar** [comment]
> So with this change both isShowingProperty and visibleProperty are readonly. 

@zepumph the `visibleProperty` isn't read-only in master. I can edit
`geometricOptics.general.view.navigationBar.phetButton.phetMenu.optionsDialogCapsule.optionsDialog.visibleProperty` in Studio and hide the dialog while keeping the dimmed filter up.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/8419308/168691731-1a0fa225-af6b-4917-ac16-557b9d9b6e11.png">

Otherwise, things are looking good in master.

**Comment by zepumph** [comment]
Oh man, I'm sorry about that. How about that?

**Comment by arouinfar** [comment]
Thanks @zepumph, looks good. I verified in master using Geometric Optics which has two dialogs - Options & About.
