### ISSUE TITLE
All Audio toggle button - need to double check the initial presentation in the code

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#804]
While working on the interaction design patterns for the Description Course, I looked more carefully at our implementation of the All Audio, toggle button in the navbar.

Sound is on by default, but is the toggle button "toggled on" by default in the code?

If not, it might make more sense to have it "toggled on" in the code, and then have learners toggle it off to turn the Sound off.

An on/off switch , rather than a toggle button might be a better interaction, all together, though I am not 100 percent sure.

Anyways, this issue to open the conversation about the best initial state for the toggle button before we have too many more new sims with sound.

@Matthew-Moore240 and discussed the situation today, and we thought a quick review with other designers and devs would be useful.

Tagging @jessegreenberg or @zepumph to ask what is the exact initial state of the All Audio toggle button?

Tagging @amanda-phet , @arouinfar , @BLFiedler to ask if you think the button should be toggled on by default since sound is on.

**Comment by jessegreenberg** [comment]
There is a Property called `audioEnabledProperty` that controls whether all audio is on or off and it is controlled by this button. The default value is `true` and the value is controlled by this button. I think that matches the state of the button graphically.

The accessible name of the button is now "All Audio". When audio is enabled, it has `aria-pressed=false` and when disabled it has `aria-pressed=true`. So the screen reader output when audio is enabled is like "All Audio, not pressed". I think this is backwards, should that be reversed? I think it is working this way because the accessible name was once "Mute Sound".

**Comment by terracoda** [comment]
Thanks @jessegreenberg for these details. This was indeed my suspicion. With screen reader software, the button’s toggled state did not seem to match when sound is actually on and off.

I completely agree that the origin of this miss-match is when we changed the label from “Mute Sound” to “All Audio”.

I also agree that the aria-pressed states should be reversed. 

Let’s do that and then I can review it and update the design pattern, too.

**Comment by terracoda** [comment]
It would be good to address this issue before we publish the next sim with sound. 

What kind of label do I need for that?

**Comment by terracoda** [comment]
Can any dev do the aria-pressed swap? If so, please re-assign as you see fit.

**Comment by samreid** [comment]
> What kind of label do I need for that?

For that we use the `status:blocks-publication` label.  I'll add the label now based on the prior comments.

**Comment by jessegreenberg** [comment]
I swapped the aria-pressed state of this button, @terracoda can you please review?

**Comment by terracoda** [comment]
Awesome. I will review as soon as I can.

**Comment by terracoda** [comment]
Sounds great in VoiceOver
<img width="823" alt="image" src="https://user-images.githubusercontent.com/1902116/168913714-85744f21-7aa0-40ca-8925-6c23a41c55d0.png">

And when All Audio is toggled off and I move focus to it, VoiceOver just says, "All Audio, toggle button"

Much better! Thanks @jessegreenberg!

Is there a chance of getting a maintenance release for affected sims with Interactive Description that have the All Audio button? Maybe we should discuss at next planninng meeting.

Of course, a couple of sims like RaP and Friction are in the publication pipeline.

**Comment by terracoda** [comment]
Do we need a new issue about maintenance releases?

**Comment by jessegreenberg** [comment]
OK great, thanks. Ill remove the "blocks-publication" label then. This issue is fine for MR. ll take a look at sims that may have this change, either manually or using the tooling but this change should be simple for maintenance releases.

**Comment by jessegreenberg** [comment]
The button name was changed on 7/13/21 with SHA 28a10c682eef20bd0a391eaec610e11999d3de07, so this would impact sims that were published after that date that support Interactive Description.

Using the automated maintenance process...
I ran `Maintenance.addNeededPachesBefore( "joist", "28a10c682eef20bd0a391eaec610e11999d3de07" )` and it produced the following list:

```js
    balloons-and-static-electricity 1.5 phet
    center-and-variability 1.0 phet-io
    circuit-construction-kit-ac 1.0 phet
    circuit-construction-kit-ac-virtual-lab 1.0 phet
    density 1.0 phet,phet-io
    equality-explorer 1.1 phet
    fourier-making-waves 1.0 phet
    geometric-optics 1.1 phet
    graphing-quadratics 1.2 phet,phet-io
    gravity-force-lab-basics 1.1 phet
    greenhouse-effect 1.0 phet-io
    john-travoltage 1.6 phet
    molecule-polarity 1.2 phet,phet-io
    molecule-shapes 1.4 phet,phet-io
    molecule-shapes-basics 1.4 phet,phet-io
    normal-modes 1.0 phet
    number-line-distance 1.0 phet
    number-play 1.0 phet
    ph-scale 1.5 phet,phet-io
    ph-scale-basics 1.5 phet,phet-io
```

Of those here are the impacted sims that support interactive description that have been published with this:
- balloons-and-static-electricity 1.5 phet
- gravity-force-lab-basics 1.1 phet
- john-travoltage 1.6 phet

That matches my memory of sims that have been published with interactive-description since july of last year. The list and change is small enough that I think it will be faster to continue manually.

**Comment by jessegreenberg** [comment]
OK, sims have been redeployed to production! Total time was a little over an hour for https://github.com/phetsims/joist/issues/804#issuecomment-1129372089.

@terracoda back to you, is there anything else for this issue?

**Comment by terracoda** [comment]
Thanks @jessegreenberg !
Awesome work. Closing.
