### ISSUE TITLE
support dynamic locale switching in toolbar

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#850]
This blocks friction phet-io

**Comment by zepumph** [comment]
I'll do this. I hit it while reviewing https://github.com/phetsims/joist/issues/838.

**Comment by zepumph** [comment]
The work here is done, but it isn't currently doing anything because of https://github.com/phetsims/joist/issues/852. @jessegreenberg please review once that work is done.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, commits to use `*StringProperty` for Toolbar strings looks good. How we handle i18n for this content is dependent on https://github.com/phetsims/joist/issues/853. Blocked until then.

**Comment by jessegreenberg** [comment]
In #853 we decided that Voicing content should be hidden when switching away from the English locale so contents of the VoicingToolbarItem do not need to support locale switching because those strings are not translatable.

In #852 I asked if it would be clearer for these non-translatable strings to be defined locally instead of nested under the `a11y` key. If so, that should be done for VoicingToolBarItem as well. This issue can be closed, we will do that there if it is best.
