### ISSUE TITLE
support dynamic locale switching in preferences panels

### ISSUE THREAD

**Issue by zepumph** [phetsims/joist#851]
this is blocking friction phet-io release.

**Comment by zepumph** [comment]
This should be all supported. I was able to test in the input and audio panels, but voicing isn't working because of https://github.com/phetsims/joist/issues/852. Please review once that issue is complete.

**Comment by zepumph** [comment]
Oh sorry! This isn't actually working. PreferencesToggleSwitch is not supportive of relayout. I'm not sure how best to support this. here is how it currently looks:

![image](https://user-images.githubusercontent.com/6856943/188034796-75fefa92-07b7-423b-bb81-a3c3a2d31a41.png)

**Comment by zepumph** [comment]
Sorry. My push had a conflict. All should be good now.

**Comment by jessegreenberg** [comment]
Thanks @zepumph commits above look good. Ill take a look at PreferencesToggleSwitch.

**Comment by jessegreenberg** [comment]
With help from @jonathanolson I implemented layout for PreferencesToggleSwitch using GridBox. I found a couple of strings in VisualPreferencesPanel that were not using Properties. And I removed some documentation about excluding some strings from i18n since they will be translatable now.

I think that is all for Preferences contents except for https://github.com/phetsims/joist/issues/852 and we will continue there. Closing.
