### ISSUE TITLE
Customize Voice Sliders are not voicing changes with keyboard interaction

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#854]
![image](https://user-images.githubusercontent.com/1902116/188667096-3678e2ca-8af0-479a-8b08-3355c5e88477.png)

The sliders that control voice Rate and voice Pitch used to voice changes when using keyboard. Now they only voice changes when using mouse input.

Here's a link to the design doc for the [Preferences Menu](https://docs.google.com/document/d/1Qu3U8IsFYn486oJUzQ71BXs_lBKZTVS5NVdLJlTK7gw/edit#heading=h.1af2t2z358dk) in case it is needed.

Assigning @jessegreenberg. Please re-assign if you are not the responsible dev.

**Comment by jessegreenberg** [comment]
Thanks @terracoda. I started to investigate this in https://github.com/phetsims/utterance-queue/issues/90, but this issue is better in joist. Moving comments over here.

> Hmm, odd - I notice that if I press the keyboard buttons slowly and wait ~1 second before releasing I do hear the responses. There must be some interruption happening.

> @zepumph helped me think through this - There is a custom Property listener in these controls that trigger the Voicingresponses. We should try to use the code in AccessibleValueHandler to trigger voicing. This could also be an opportunity to add Voicing to Slider directly so that we get Voicing from its DragListener for mouse/touch input. voicingOnEndResponse is public from AccessibleValueHandler and is probably a good place to start.

**Comment by zepumph** [comment]
This issue is blocking friction and RAP releases as far as I know.

**Comment by jessegreenberg** [comment]
OK, this was done in the above commits. To summarize, I added Voicing to Slid by using `voicingOnEndResponse`. The hard part was getting it to work with SliderTrack. I had to make `valueOnStart` an arg for `voicingOnEndResponse` so that it could be used without a references to Slider or a subtype of AccessibleValueHandler.

After these changes I updated the sliders in VoicingPanelSection.

@zepumph can you please review these changes to AccessibleValueHandler, Slider, SliderTrack, and VoicingPanelSection?

**Comment by zepumph** [comment]
This all looks excellent! Thank you so much.
