### ISSUE TITLE
Arrow keys not moving focus to new Tab in Preferences Menu (Firefox and Mac OS)

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#894]
Just happened to notice that the Arrow keys are not moving focus to the next Tab in the Preferences Menu (Firefox 108.0.1 and Mac OS 12.2.1)

This is in published sims (found it in GFLB launched from PhET website), and all sims on Master.

The issue is not happening in Safari or Chrome.
The Arrow keys of other interactions, e.g., moving grabbed balloon, and cycling through radio buttons are working fine in Firefox.

**Comment by pixelzoom** [comment]
macOS 12.2.1 is ancient, released 1/26/2022. Update to at least macOS 12.6.1 (the most recent [and final] version of macOS 12) and see if the problem persists. (edit

**Comment by jessegreenberg** [comment]
I tried on a Mac I have for debugging and was not able to reproduce but it was on 11.6.2 (very old). Ill see how far I can update this machine and try again.

**Comment by jessegreenberg** [comment]
I tried macOS 11.7.2 with FF 108.0.1 and did not see this. My Mac is stuck looking for updates. @terracoda lets try to get more info from your machine soon.

**Comment by jessegreenberg** [comment]
Taliesin and I did some investigating on her machine. We were in PreferencesTabs.ts around the keyboard listener that moves focus between the buttons. We saw we hit the `keydown` event but NOT the `keyup` event. For some reason, we get a `blur` event between the two and focus is lost entirely.

Very strangely, I saw that if we add a `event.domEvent.preventDefault()` to the `keydown` listener the problem is fixed. This shouldn't be necessary.

@terracoda mentioned she was using VoiceOver earlier in the day. VoiceOver is good at intercepting events and we have seen it cause system bugs from being used once, even when it is turned off. I have a theory that the next time @terracoda restarts her computer (and before using VoiceOver) this problem will be gone.

**Comment by terracoda** [comment]
I am still losing focus after updating to MacOS 12.6.2
I have a MacBook Pro Chip Apple M1 in case that matters.

**Comment by terracoda** [comment]
I just shutdown my computer and re-booted to make sure. 
I am still losing focus when I use the Arrow keys to move to a new tab.

**Comment by jessegreenberg** [comment]
Hmm, OK thanks. That rules out my theory in https://github.com/phetsims/joist/issues/894#issuecomment-1355644750.

@KatieWoe would you mind seeing if you can get this to happen in macOS + FireFox?

**Comment by terracoda** [comment]
Ok, @jessegreenberg found the issue. It is a Firefox Preferences setting!
Under the Browsing section in the Firefox Preferences Menu, one must uncheck the setting:
- "Always use cursor keys to navigate within pages"
![image](https://user-images.githubusercontent.com/1902116/208478601-f2318d4c-af8f-4059-8e84-a3ac7d7b4d93.png)

I had that Preference checked, so the arrow keys were trying to navigate content in the page rather than move focus.

**Comment by terracoda** [comment]
Closing.
