### ISSUE TITLE
NavigationBarScreenButton interactive highlight does not support dynamic text

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/joist#926]
In https://github.com/phetsims/geometric-optics/issues/470, QA discovered that the interactive highlight for navbar buttons does not support dynamic text.  It is not resizing when the button label changes.

@jessegreenberg identified this as a problem that is specific to NavigationBarScreenButton:
 
> Generally the highlight does resize to fit the Node's bounds. But that isn't happening here because NavigationBarScreenButton is using a custom highlight that does not update.

**Comment by pixelzoom** [comment]
When this is fixed, please identify shas for cherry-picking to geometric-optics 1.3, to address https://github.com/phetsims/geometric-optics/issues/470.

**Comment by jessegreenberg** [comment]
There is a custom focus highlight in the NavigationBarScreenButton so that the highlight is not cut off below the nav bar but it wasn't updating with dynamic layout. Fixed in the above commit. The highlight shape was changed slightly so that it does not cover up the title text when longer strings get scaled down. The bottom of the highlight is cut off a little but @amanda-phet and I think it is acceptable and the best option with limited space in the nav bar.

@Nancy-Salpepi can you please confirm master? If it is OK to you it is ready to cherry-pick into geometric-optics.

**Comment by Nancy-Salpepi** [comment]
Looks good in master to me @jessegreenberg 🙂

**Comment by jessegreenberg** [comment]
Awesome, thanks! @pixelzoom can you please review the code change? If it looks OK https://github.com/phetsims/joist/commit/2e895f32f3e08127c47da57542ad9c1feaf29954 is the fixing SHA.

**Comment by pixelzoom** [comment]
Looks good to me in master, thanks! 

Closing this issue, and will patch geometric-optics 1.3 over in https://github.com/phetsims/geometric-optics/issues/470.
