### ISSUE TITLE
Preferences Menu Layout - On/Off Swithces too far from name/label.

### ISSUE THREAD

**Issue by terracoda** [phetsims/joist#969]
Something has moved the toggle switches in the Preferences Menu too far from their actual names.

Here's a screenshot of GFLB from PhET Bookmarks
![Screenshot 2024-05-27 at 13 04 14](https://github.com/phetsims/joist/assets/1902116/64b69e91-42e1-4389-a3af-2119b26dabea)

Here's a screenshot of the published sim,
![Screenshot 2024-05-27 at 13 07 54](https://github.com/phetsims/joist/assets/1902116/a388c148-0280-4c9c-b91e-7f067996eb46)

I think the toggle switched need to above the paragraph that's describing the switch's function, or right next the name.
Currently, on Main, the Voicing toggle switch is right next the the Sound toggle switch which is really confusing.

**Comment by terracoda** [comment]
@jessegreenberg, tagging you because, I am not sure who to assign to this issue? 
Not sure when/how the layout changed.

This issue is appearing on all sims with Voicing on Main, and not in published sims.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, I will take a look.

**Comment by jessegreenberg** [comment]
I think this was introduced from https://github.com/phetsims/joist/commit/af68dfb506769e882b56df925f7f994097be7a8a for https://github.com/phetsims/number-line-integers/issues/118. It looks better if I remove the `minContentWidth`. @marlitas or @jonathanolson is it OK if we remove that value and do you know why it was added for NLI?

**Comment by jessegreenberg** [comment]
Maybe it is because some controls are nicely aligned like this:

![image](https://github.com/phetsims/joist/assets/6396244/e5c0c091-10f0-4917-b748-8c3cecf23e42)

**Comment by jessegreenberg** [comment]
@jonathanolson and I discussed, we can add an option to PreferencesControl to remove `stretch` and `minContentWidth` for this layout case if needed.

**Comment by jessegreenberg** [comment]
Yes, that makes sense @marlitas. But I went ahead and made this commit so that this layout doesn't get published in more sims. Would you mind reviewing the change? Do you have a recommendation for a better long term change?

The new option is `allowDescriptionStretch`, default `true` because it seems like most sim usages (which most devs will encounter) do want the stretch. I added `allowDescriptionStretch: false` to the usages in joist that needed it and tested. I didn't review any other sim usages to see if this was needed.

**Comment by marlitas** [comment]
@jessegreenberg okay that seems fair. The changes look good. I think we can close this issue.
