### ISSUE TITLE
Review description i18n strategies

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/joist#985]
We are exploring ways to make our description strings translatable.

Description strings are dynamic with string patterns that have multiple variables. They are often written in natural language. They will require transformations and logic to handle different languages and contexts.

In order to support this complexity, we are considering a path where the translator writes code to handle these cases.

We are proposing a setup where accessibility strings would appear in a file like this:
https://github.com/phetsims/ph-scale/blob/descriptionProperties/js/common/view/description/PHScaleDescriptionStringsEN.ts

The translator would then write an associated translation file like this:
https://github.com/phetsims/ph-scale/blob/descriptionProperties/js/common/view/description/PHScaleDescriptionStringsES.ts

There is a mapping that returns a DerivedProperty, so that strings update when locale and other dependencies change. Usages would look like this:
https://github.com/phetsims/ph-scale/blob/bb087c50c555b8a75ea6800ea7fe285a8d8e527a/js/macro/view/MacroScreenView.ts#L125-L132

and like this:
https://github.com/phetsims/ph-scale/blob/bb087c50c555b8a75ea6800ea7fe285a8d8e527a/js/common/view/SolutionNode.ts#L61-L65

So the idea is that each repo has a directory like this:
```
  /description
    RepoDescriptionStrings.ts -> Maps locale to string file to use.
    RepDescriptionStringsEN.ts -> Contains the implementation for strings in English
    RepDescriptionStringsES.ts -> Contains the implementation for strings in Spanish
    RepDescriptionStringsFR.ts -> Contains the implementation for strings in French
    ... and so on.
```

With this approach, translators would presumably set up a development environment, write translations in TypeScript, and then submit a pull request to the repo.

We are uncertain about the approach and requirements. We want to review the direction and technical details with the broader team. Here are some things we are wondering about:
  - Is it a requirement that all translations for accessibility strings have perfect grammar? If not, we might(?) be able to simplify and use existing support from Rosetta.
  - Is it acceptable that translators need to set up a development environment to submit translations for these strings?
  - Does this seem like a reasonable organization for the description strings for simulation development (scalability, maintainability, etc)?
  - An alternative to requiring code is to enumerate all strings for all cases in the strings file. That seems like an explosion of new strings, but is that preferable?
  - Should the "static" accessibility strings go with our visual strings so that at least subset of strings is more easily translatable?
  - What other thoughts do you have at this point?

Related to work happening in #941.

**Comment by arouinfar** [comment]
Glad to see the i18n discussion is happening! I have a few thoughts I’d like to share.

> Is it acceptable that translators need to set up a development environment to submit translations for these strings?

If we hope to leverage our existing trusted translators, I don’t think so. It took significant effort for designers to get their local dev environments up and running, including many developer hours to assist. However, if the translators are recruited from the SceneryStack community, this is likely a non-issue.

> Should the "static" accessibility strings go with our visual strings so that at least subset of strings is more easily translatable?

I like this idea, especially as we experiment with adding accessible names and help text to more sims. In general, these strings tend to be static (or at least minimally dynamic) and are on par with the types of strings our translators are used to working with. 

Many accessible names tend to match the exact string used in the sim’s view, and I would encourage us to use the existing string key to avoid duplication of code and work for the translator. Another potential benefit would be in PhET-iO. If a client customizes the name of a checkbox, its accessible name would update for free if the same string key were used for both. (We don’t expose any a11y strings to PhET-iO clients.)

> What other thoughts do you have at this point?

The [soluteMap](https://github.com/phetsims/ph-scale/blob/descriptionProperties/js/common/view/description/PHScaleDescriptionStringsEN.ts#L8-L21) used in the description duplicates the solute names in the sim’s [strings file](https://github.com/phetsims/ph-scale/blob/main/ph-scale-strings_en.json#L14-L49). Have we considered ways to reuse strings like this in the description?

**Comment by brettfiedler** [comment]
Just for consideration in discussion, I created a pull request creating a French translation file using only the github interface. It does not address everything by any means, but presents some possibilities for easing use by those without a development environment.

https://github.com/phetsims/ph-scale/pull/298

**Comment by kathy-phet** [comment]
Thanks for putting together this example for discussion. 

In terms of requirements, I think with the "PhET" hat on we can think about how Rosetta might be leveraged/extended for accessible name and helptext and possibly more complex things, but Rosetta is very much a PhET-specific thing for our build and translation process (at least from my understanding since we have to store strings and all sorts of things) . 

We will need to put our "POSE 2" hat on and make sure that we have a process/structure that allows translation in a non-Rosetta world, where a different organization might build their own Rosetta type tooling or where they may translate the .ts strings file.

**Comment by emily-phet** [comment]
Thanks @jessegreenberg for this issue/thread. 

> Is it a requirement that all translations for accessibility strings have perfect grammar? If not, we might(?) be able to simplify and use existing support from Rosetta.
While I don't think we need to have a process to verify grammar in non-English languages, I do think the expectation should be that translations follow language-specific grammar rules. This is because we already simplify the text/phrases etc. largely to the minimum. The more sparse the language, the greater the likelihood that misunderstanding can result from a grammar issue. 
> Is it acceptable that translators need to set up a development environment to submit translations for these strings?
I think it's not unreasonable to limit translations of full description to those comfortable setting up/working in a dev environment. For those not comfortable but motivated to try, they can eventually reach out to the SceneryStack community and ideally get support that isn't always directly from PhET staff. Translation of description is much more comparable to asking someone to translate a children's book or some other comprehensive text than to translate a handful of strings. They need to want to engage with the context, etc. in a way that current translators are not being asked to do so I think it's fair to consider translation of full description as a task unique from what is currently done by the trusted translation, and some (maybe many) won't want to or be able to do that task...we'll need to invite and provide some (static) support those wanting to do this different taks.
> Does this seem like a reasonable organization for the description strings for simulation development (scalability, maintainability, etc)?
> An alternative to requiring code is to enumerate all strings for all cases in the strings file. That seems like an explosion of new strings, but is that preferable?
I can imagine this being beneficial in sims with a relatively small number of objects (john travoltage), but if a sim gets much more complicated than that it will introduce hundreds, and potentially thousands of phrases for sims. So I don't see this as a practical way forward for translators, but being able to generate a subset of example sentences, or to generate a list that is used for other purposes may have some benefits. 
> Should the "static" accessibility strings go with our visual strings so that at least subset of strings is more easily translatable?
I think Kathy's comment above is relevant to this. Sounds like there are some benefits for PhET/PhET-iO in doing this, but none for outside devs in the SceneryStack community.
> What other thoughts do you have at this point?
Just a thought. There's likely no perfect solution, and probably multiple good-enough solutions. If we consider our work in getting description and description translation as a feature of sims, as setting the baseline of linguistic architecture that future LLM-powered technologies interface with for later automated translation, training for generating initial draft descriptions, baseline linguistic models for speech interfaces, etc., I think that can help everyone be clear that we don't necessarily the perfect, or ideal, or maybe even "best" solution. Rather, we need a "good enough" solution that we all feel comfortable with and can move forward with. I would guess within the next 5 years there will be such significant changes to development tooling that if we waiting a year or two we would choose a different path anyway...so let's pick a "good enough" path now and move forward to eventually supporting translators in getting these strings translated!

**Comment by jessegreenberg** [comment]
Thanks for the issue comments and discussion today everyone. A recording of the meeting will be shard in the description-tooling slack channel.

In addition, here are the main points I noted during discussion. Two most important take-aways (IMO) are at the top.

- **In general, we should put as much content in the JSON as possible.** This will get more content translated because the process is more accessible.
- **We should be able to make every string translatable with Roseta (using JSON), while ALSO adding a way to further customize strings.** That could be through code, or some kind language/library [like this one](https://shopify.github.io/liquid/). This will make most content easily translatable for most languages/cases.
- Accessible names and help text can be made translatable by going through our normal translation process.
- It is understood that the proposed approach requires significant expertise, and we would receive fewer translations for this content.
- Keeping strings in JSON is still open for SceneryStack. Anyone can edit these files in their own sims/apps.
- It was suggested that we break up our accessibility features into "layers". That will make it easier for the SceneryStack community to understand. As we roll that out, we will also have a better understanding of what is required for i18n.
- One approach could be just to make all accessibility strings translatable and see how it goes. Without changing much in Rosetta, other than maybe showing the a11y-view. If a translator says something is impossible, then we make it possible by adding strings in JSON.
- We should be careful about the review process when we receive pull requests. Be very careful about security, that the code can run, that the descriptions are accurate, good for pedagogy. That will be a manual review process and will be challenging in languages we do not understand.

Next steps:
- Schedule a translation test with a collaborator to learn more about needs.
- Investigate a fallback strategy where ALL strings are presented in JSON but we offer a way to override if needed and the user has expertise.
- Do some research to see how other organizations handle i18n and dynamic strings.

**Comment by pixelzoom** [comment]
> * Do some research to see how other organizations handle i18n and dynamic strings.

In your search, you might also want to include localization, or i10n.  PhET tends to lump everything under the term i18n, but i18n and i10n are different aspects of adapting software to different locales. https://en.wikipedia.org/wiki/Internationalization_and_localization

As a data point...  I've worked with a number of organizations over the years that were doing UI i18n and i10n.  In every case, the pattern was some variation of what PhET is doing for UI strings. That is, put the strings in one or more "declarative" files (no logic, no code) where they are accessed via a fixed identifier (key) and identified by locale. The fixed identifier is used in the code. Locale (set via the application or more commonly via the OS) determines which set of strings are used.  Actually translating the strings varied from organization to organization.  But most had paid translators, and translations were bundled into product releases (nothing as immediate as PhET's process).

You may also want to investigate the APIs provided by Apple, Microsoft, et. al. for Swift, Objective C++, C#, etc.  Again, I think you'll find variations of what PhET is doing for UI strings.

**Comment by pixelzoom** [comment]
In Slack#description, @emily-phet asked for feedback on this issue for the purposes of making a decision on which approach to proceed with.

I realize that dynamic description is a difficult problem, and that the logic itself may need to be localized.  But an approach that requires translators to write code is (imo) a non-starter.  We've discussed the reasons previously -- the skills required to write code and test it, the number of translators that have those skills, the burden on PhET to review and accept pull requests,...

In addition to the complexities of requiring translators to write code... Has PhET considered that the cost/complexity that logic-based translation will add to changing/maintaining descriptions?  For example, if PhET adds/changes a feature that affects description, how will the logic in the translated files be updated? Is PhET going to attempt that? Or will translators be required to revise their translation? How do you get them updated in a timely manner? Does that need to happen before PhET can republish a sim? ...  Even with static visual strings, changing something as simple as a string key in the JSON file has a huge associated cost, and PhET has historically avoided making those changes at all costs.  Adding logic/code to translations makes avoiding such changes impossible, and greatly increases the cost and complexity. 

My recommendation is to focus on "Tier 1" description, which can be accomplished using the same localization pattern that is used for visual strings (JSON file, etc.)   Roll that out to the POSE/SceneryStack community and see what traction it gets.  
Wait on logic-based translation until you've defined the other description tiers. Explored ways to make those tiers less dependent on logic. Be willing to compromise on descriptions that are "good enough" when they don't involve logic and reduce cost/complexity.

**Comment by jessegreenberg** [comment]
Thank you for the notes here everyone. They were reviewed carefully as we discussed in a sub team. We are in agreement that requiring translators to write code, and importing language specific typescript files into sim code is **not** the way to go.

In #990, we reviewed other formats and JavaScript libraries backed by ICU. We decided that [Fluent.js](https://projectfluent.org/) is the most promising library and format. We are going to try it out in a few sims and get feedback from translators to see how successful that is.
